import type { ExerciseDefinition } from '@/types/exercise-engine'
import { DEFAULT_SCORING_RULES } from '@/types/exercise-engine'
import { NUMBERS_DATASET } from '@/lib/exercise-engine/datasets/numbers'

export const FLASH_NUMBERS_DEFINITION: ExerciseDefinition = {
  id: 'flash-numbers',
  labId: 'quantum-speed-reading',
  title: 'Flash Numbers™',
  description: 'A number flashes for a fraction of a second. Identify it from four choices. Digit count increases as accuracy improves.',
  trainsAbility: 'Numerical processing speed',
  exerciseType: 'flash',
  contentType: 'number',
  interactionType: 'multiple-choice',
  dataset: NUMBERS_DATASET,
  adaptiveRules: {
    increaseSpeedAbove: 90,
    decreaseSpeedBelow: 70,
    minSpeedMs: 50,
    maxSpeedMs: 500,
    defaultSpeedMs: 500,
    itemsPerSession: 20,
    minAccuracyToComplete: 60,
  },
  speedMode: 'adaptive',
  scoringRules: DEFAULT_SCORING_RULES,
  intelligenceDimension: 'reading',
  href: '/labs/quantum-speed-reading/rapid-visual-intelligence/flash-numbers',
  labHref: '/labs/quantum-speed-reading/rapid-visual-intelligence',
  locale: 'en',
  i18nKeys: {
    title: 'exercise.flashNumbers.title',
    description: 'exercise.flashNumbers.description',
    instruction: 'exercise.flashNumbers.instruction',
    startLabel: 'exercise.common.start',
    pauseLabel: 'exercise.common.pause',
    resumeLabel: 'exercise.common.resume',
    exitLabel: 'exercise.common.exit',
    correctLabel: 'exercise.common.correct',
    incorrectLabel: 'exercise.common.incorrect',
    completedLabel: 'exercise.flashNumbers.completed',
    practiceAgainLabel: 'exercise.common.practiceAgain',
    questionPrompt: 'exercise.flashNumbers.questionPrompt',
    keyboardHint: 'exercise.common.keyboardHint',
  },
  config: {},
}
