import { describe, expect, it } from 'vitest'
import { createMentorOrchestrator, createMentorPipeline } from '@/features/ai-mentor/pipeline'
import { makeDocument } from '@/features/learning-intelligence/testFixtures'
import { createMentorAIProviderAdapter } from './MentorAIProviderAdapter'

// The full "Conversation → AI Mentor → Provider Registry → Provider
// Factory → Provider Adapter → Mock Provider → Mock Response" chain,
// exercised for real: a real MentorOrchestrator (ai-mentor, unmodified)
// running a real MentorPipeline (ai-mentor, unmodified), with only the
// `providerAdapter` dependency swapped — via the existing DI seam, no
// source file in ai-mentor edited — for this bridge's
// MentorAIProviderAdapter, which itself resolves through a real
// ai-provider ProviderRegistry + ProviderFactory to a real Chunk 3
// MockProviderAdapter. Nothing here is a UI test; this proves the
// wiring end-to-end at the library level.
describe('AI Mentor ↔ AI Provider Layer — end-to-end (mocked)', () => {
  it('produces a mentor reply generated by the real ai-provider MockProviderAdapter pipeline', async () => {
    const orchestrator = createMentorOrchestrator({
      pipeline: createMentorPipeline({ providerAdapter: createMentorAIProviderAdapter() }),
    })

    const document = makeDocument()
    const { session, conversation } = await orchestrator.startMentorSession(document, 'project-1')
    expect(session.status).toBe('active')

    const uiResponse = await orchestrator.sendMentorMessage(conversation.id, 'What should I study next?')

    // The mock text format is createMockProviderAdapter's own
    // (`[mock <displayName> reply via <modelDisplayName>] Acknowledged: "..."`)
    // — asserting on it here is what proves the reply really traveled
    // through ai-provider's MockProviderAdapter, not ai-mentor's own
    // separate trivial mock (@/features/ai-mentor/conversation/MockProviderAdapter,
    // which produces entirely different wording).
    expect(uiResponse.reply.content).toContain('Mentor Bridge Mock Provider')
    expect(uiResponse.reply.content).toContain('Mentor Bridge Mock Model')
    expect(uiResponse.reply.role).toBe('mentor')

    await orchestrator.endMentorSession()
  })

  it('is fully deterministic — the same inputs produce the same mock reply content shape twice', async () => {
    const runOnce = async (): Promise<string> => {
      const orchestrator = createMentorOrchestrator({
        pipeline: createMentorPipeline({ providerAdapter: createMentorAIProviderAdapter() }),
      })
      const { conversation } = await orchestrator.startMentorSession(makeDocument(), 'project-1')
      const uiResponse = await orchestrator.sendMentorMessage(conversation.id, 'Same question')
      return uiResponse.reply.content
    }

    const first = await runOnce()
    const second = await runOnce()
    expect(first).toBe(second)
  })

  it('never calls a real network — the reply is produced entirely in-process', async () => {
    const originalFetch = globalThis.fetch
    let fetchCalled = false
    globalThis.fetch = (() => {
      fetchCalled = true
      throw new Error('fetch() must never be called — this sprint is mock-only')
    }) as typeof fetch

    try {
      const orchestrator = createMentorOrchestrator({
        pipeline: createMentorPipeline({ providerAdapter: createMentorAIProviderAdapter() }),
      })
      const { conversation } = await orchestrator.startMentorSession(makeDocument(), 'project-1')
      await orchestrator.sendMentorMessage(conversation.id, 'Hello')
      expect(fetchCalled).toBe(false)
    } finally {
      globalThis.fetch = originalFetch
    }
  })
})
