// Reading Intelligence Engine™ Upgrade — Sprint-3: Reading Experience
// Engine™. Difficulty Progression Engine™'s four real, ordered tiers —
// calculated purely from already-real Learning Asset fields
// (`LearningAssetObject.difficulty`/`.importance`), never regenerated by
// AI. See internal/computeDifficultyLevel.ts.
export const DIFFICULTY_LEVELS = ['easy', 'moderate', 'advanced', 'mastery'] as const

export type DifficultyLevel = (typeof DIFFICULTY_LEVELS)[number]
