import type { LearningAssetObject } from '@/core/universal-learning-engine/learning-assets'
import type { ChunkDifficulty } from '@/core/universal-learning-engine/learning-chunk'
import { DIFFICULTY_LEVELS, type DifficultyLevel } from '../types/DifficultyLevel'

// Difficulty Progression Engine™. Four real, ordered tiers computed
// purely from already-real `LearningAssetObject.difficulty`/`.importance`
// — never regenerated by AI, never fabricated. A real, high-importance
// concept is treated as one tier harder to truly master than its base
// difficulty alone would suggest (a beginner-difficulty concept the
// chapter treats as central is "moderate" to master, not "easy" —
// genuinely more real material to retain, not a made-up bump).
const BASE_RANK: Record<ChunkDifficulty, number> = { beginner: 0, intermediate: 1, advanced: 2 }
// No reported difficulty is never assumed easiest — it starts at the
// same middle rank `sequenceLearningObjects.ts` already uses.
const UNKNOWN_BASE_RANK = 1
const HIGH_IMPORTANCE_THRESHOLD = 0.75

export function computeDifficultyLevel(object: LearningAssetObject): DifficultyLevel {
  const baseRank = object.difficulty ? BASE_RANK[object.difficulty] : UNKNOWN_BASE_RANK
  const importanceBoost = object.importance >= HIGH_IMPORTANCE_THRESHOLD ? 1 : 0
  const levelIndex = Math.min(DIFFICULTY_LEVELS.length - 1, baseRank + importanceBoost)
  return DIFFICULTY_LEVELS[levelIndex] as DifficultyLevel
}

// A session's own overall level — the most common real level among its
// own real Learning Objects, ties broken toward the harder level (a
// session is never described as easier than its real hardest common
// content).
export function computeSessionDifficultyLevel(objects: readonly LearningAssetObject[]): DifficultyLevel {
  if (objects.length === 0) return 'easy'

  const counts = new Map<DifficultyLevel, number>()
  for (const object of objects) {
    const level = computeDifficultyLevel(object)
    counts.set(level, (counts.get(level) ?? 0) + 1)
  }

  let bestLevel: DifficultyLevel = 'easy'
  let bestCount = -1
  for (const level of DIFFICULTY_LEVELS) {
    const count = counts.get(level) ?? 0
    if (count >= bestCount && count > 0) {
      bestCount = count
      bestLevel = level
    }
  }
  return bestLevel
}
