import type { ReadingUnit } from '@/features/reading-engine/types'

// Guided Paragraph Reading Mode™ dataset — Quantum Speed Reading™ V2, the
// Master Reading Engine's fifth and final mode. Deliberately its own
// folder/content, separate from every other mode's dataset (including
// Paragraph Reading Mode's own 5 passages) — no shared files, no route
// collision, and no topic overlap with Paragraph Reading's content.
//
// Same "True Multi-Line Comfort Window" convention as Paragraph Reading:
// 5 real, hand-written, single-topic passages (~190-210 words / 15-20
// lines at a comfortable reading width), each one ReadingUnit = one block
// for the Comprehension Checkpoint system. What's different about this
// mode is purely presentational — see GuidedParagraphReadingModeCanvas.tsx
// for the line-sweep guided pacing bar this mode adds on top of the same
// word-by-word engine pacing.
const GUIDED_PARAGRAPH_READING_MODE_PASSAGES: readonly string[] = [
  'Rereading a passage is often treated as a failure, a sign that the first attempt did not work. In practice it is closer to the opposite: a deliberate second pass, chosen rather than forced, is one of the most reliable ways real understanding actually forms. The first time through, a reader is mostly occupied simply following the sentence, tracking who is speaking, what happened, what comes next. There is little spare attention left over for noticing structure, tone, or the quieter connections between one idea and another. A second pass changes this completely. Freed from the basic work of simply keeping up, the mind can finally notice how an argument builds, where a detail was planted earlier for later use, or why a particular word was chosen instead of an easier one. Skilled readers reread constantly, often without even announcing it to themselves, treating a second look as a normal part of reading rather than an embarrassing correction. Readers who consider rereading a personal failure tend to avoid it, and end up carrying a thinner, more fragile understanding of everything they read as a result. Giving a passage permission to be read twice is not slower reading. It is often the fastest route to actually understanding it the first real time.',
  'Most people imagine their eyes gliding smoothly across a line of text, the way a finger might trace along a sentence. In reality, the eyes move in short, rapid jumps, pausing briefly on one cluster of words, jumping forward, pausing again, several times a second. These brief pauses, not the jumps themselves, are where actual reading happens; almost nothing is absorbed while the eyes are in motion between one stop and the next. A slow, uncertain reader typically makes small jumps, landing on only one or two words at a time, and sometimes jumps backward to recheck something already seen. A confident, well-practiced reader makes longer jumps, landing on wider clusters of words, and rarely needs to double back. This is not a different set of eyes; it is a different, learned pattern built through repeated practice, the same way a skilled driver learns to glance further down a road than a nervous beginner does. Understanding this changes what practice should actually target. The goal was never to move the eyes faster in some raw physical sense. It is to train them to land less often, take in more with each landing, and trust the first look enough to stop circling back to check it.',
  'It feels efficient to read with a second task running alongside it, a video paused nearby, a conversation half-followed in another room. The mind convinces itself both things are being handled at once. What is actually happening is quieter and more costly: attention is switching rapidly back and forth, and each switch carries a small, invisible tax paid in lost comprehension. A paragraph read this way is technically seen in full, every word passed in front of the eyes, yet very little of it survives the session intact. The reader often has to return to the same page later, genuinely unsure whether it was ever read at all. This is not a question of trying harder or feeling more disciplined in the moment; divided attention behaves this way for everyone, regardless of how capable a reader believes themselves to be. The fix is rarely dramatic. It is usually as simple as closing one tab, silencing one notification, or choosing a slightly less convenient but quieter room for twenty honest minutes. Reading is one of the few tasks where doing noticeably less at once reliably produces noticeably more understanding by the end of it, a trade most people would happily make if they actually noticed it was on offer.',
  'Motivation is an unreliable foundation for a daily reading habit, since it naturally rises and falls for reasons that have nothing to do with the book itself. A small, repeated ritual works far better, because it removes the daily decision entirely. The same chair, the same time of day, even the same cup of tea beforehand, all quietly signal to the mind that reading is about to happen, long before the first sentence is even reached. Over time the ritual itself becomes the real trigger, doing work that willpower alone was never going to sustain on its own. This is why so many pieces of advice about reading more insist on small, oddly specific details, ten minutes after breakfast, always in the same seat by the window, rather than vague, larger goals like reading more this year. The specific details are not decoration. They are the actual mechanism, giving the habit something concrete and repeatable to attach itself to. A reader who waits to feel like reading before starting will read only when the mood happens to cooperate. A reader who has built even a small, boring ritual around it will find themselves reading on the ordinary days too, which, added up honestly over a year, turn out to be most of them.',
  'Finishing every book that gets started is often treated as a matter of basic discipline, as though stopping partway were a small personal failure. This idea deserves far less authority than it usually gets. Time spent finishing a book that has already stopped offering anything real is time taken directly away from something that might have mattered more, and no one earns a meaningful reward simply for reaching a final page out of stubbornness. A reasonable test is whether the book is still doing real work: teaching something new, holding real interest, or building toward a payoff genuinely worth the remaining pages. When none of these are true anymore, continuing rarely serves the reader; it usually only serves a private, quiet sense of obligation to a decision made much earlier, often before enough was even known to judge the book fairly. Learning to set a book aside without guilt is, in its own quiet way, a real reading skill, not a lapse in one. It protects attention for the books that actually deserve it, and it keeps reading itself feeling like a choice being made again and again, rather than an old debt being slowly repaid one page at a time.',
]

export const GUIDED_PARAGRAPH_READING_MODE_UNITS: readonly ReadingUnit[] = GUIDED_PARAGRAPH_READING_MODE_PASSAGES.map((text, index) => ({
  id: `guided-passage-${index}`,
  text,
}))

export const TOTAL_GUIDED_PARAGRAPH_READING_MODE_UNITS = GUIDED_PARAGRAPH_READING_MODE_UNITS.length
