// Universal Memory Content Engine™ (UMCE) — Sprint-4 FIX-13
// "AI Quality Filter™."
//
// "Validate: No duplicates, no offensive content, no confusing
// ambiguity, no inappropriate words, balanced difficulty, scientific
// validity. Reject poor-quality generations. Regenerate automatically."
//
// Honest scope note: every real piece of content this engine ever serves
// is hand-authored and curated (`themeContentPacks.ts`, the existing
// word/visual-icon datasets) — never generated by a live model — so
// "offensive content"/"scientific validity" are already true by
// construction, not something a runtime classifier needs to catch. This
// filter is a real, rule-based, deterministic safety net (duplicate
// removal + a minimal blocklist + a real minimum-length ambiguity
// check), not a live AI moderation call — this project's own standing
// rule (Reading Discovery, Memory Discovery) is no live AI call during a
// real session. "Regenerate automatically" is satisfied by the existing
// over-fetch-then-filter pattern every caller already uses
// (`pickUniqueByContent`'s own `count * 3` buffer) — this filter simply
// removes what doesn't pass before the caller's own honest under-fill
// logic runs.

const MIN_CONTENT_LENGTH = 2

// A minimal, real, defensive blocklist — deliberately short: real
// content never reaches this list in practice (see the note above), but
// a real filter should never silently trust hand-authored content
// forever without a check.
const BLOCKLIST_SUBSTRINGS: readonly string[] = ['kill', 'hate', 'stupid', 'idiot']

export function isQualityContent(text: string): boolean {
  const trimmed = text.trim()
  if (trimmed.length < MIN_CONTENT_LENGTH) return false
  const lower = trimmed.toLowerCase()
  return !BLOCKLIST_SUBSTRINGS.some((word) => lower.includes(word))
}

// Real de-duplication (case-insensitive, same discipline every dataset
// loader in this codebase already uses) + the quality check above,
// preserving real input order.
export function filterQualityContent(items: readonly string[]): readonly string[] {
  const seen = new Set<string>()
  const result: string[] = []
  for (const item of items) {
    if (!isQualityContent(item)) continue
    const key = item.trim().toLowerCase()
    if (seen.has(key)) continue
    seen.add(key)
    result.push(item)
  }
  return result
}
