import type { ReadingUnit } from '@/features/reading-engine/types'

// Vertical Word Reading Engine™ — a genuine 25-category vocabulary
// library. Real, hand-authored English words and a handful of natural
// short compound terms only (no AI, no lorem ipsum) — deliberately not
// shared with or derived from any other dataset in this app. Each
// category holds at least 250 distinct real terms, chosen so a session
// at this app's own default 250 WPM pace runs a genuine 60+ second
// continuous read (verified in this file's own test suite) — a fixed
// word count can't hold "60-90 seconds" across the *entire* user-
// selectable 100-500 WPM range (no dataset in this app promises that;
// Flash Recall Sprint's own passages are calibrated the same way, against
// a representative band rather than every possible WPM). A minority of
// entries are natural short compound terms (e.g. "Free Will", "Habeas
// Corpus") where a field's real vocabulary is genuinely two words — the
// shared reading engine already paces a unit's dwell time by its own real
// word count, so this costs nothing to support and reads more
// authentically than forcing everything into a single word.
export type VerticalWordReadingCategory = {
  id: string
  label: string
  words: readonly string[]
}

export const VERTICAL_WORD_READING_CATEGORIES: readonly VerticalWordReadingCategory[] = [
  {
    id: 'neuroscience',
    label: 'Neuroscience',
    words: [
      'Neuron', 'Synapse', 'Axon', 'Dendrite', 'Myelin', 'Cortex', 'Cerebellum', 'Amygdala',
      'Hippocampus', 'Thalamus', 'Hypothalamus', 'Brainstem', 'Neurotransmitter', 'Dopamine', 'Serotonin', 'Norepinephrine',
      'Acetylcholine', 'Glutamate', 'Cognition', 'Plasticity', 'Neuroplasticity', 'Neurogenesis', 'Myelination', 'Potentiation',
      'Depression', 'Excitation', 'Inhibition', 'Threshold', 'Impulse', 'Signal', 'Circuit', 'Pathway',
      'Network', 'Connectome', 'Wiring', 'Firing', 'Cascade', 'Receptor', 'Ligand', 'Channel',
      'Gradient', 'Membrane', 'Potential', 'Voltage', 'Current', 'Polarization', 'Depolarization', 'Repolarization',
      'Refractory', 'Latency', 'Reflex', 'Arousal', 'Vigilance', 'Attention', 'Perception', 'Sensation',
      'Nociception', 'Proprioception', 'Interoception', 'Homeostasis', 'Regulation', 'Modulation', 'Adaptation', 'Habituation',
      'Sensitization', 'Consolidation', 'Encoding', 'Retrieval', 'Recall', 'Recognition', 'Working', 'Episodic',
      'Semantic', 'Procedural', 'Implicit', 'Explicit', 'Declarative', 'Amnesia', 'Dementia', 'Degeneration',
      'Atrophy', 'Lesion', 'Trauma', 'Concussion', 'Seizure', 'Epilepsy', 'Migraine', 'Stroke',
      'Ischemia', 'Hypoxia', 'Inflammation', 'Glia', 'Astrocyte', 'Microglia', 'Oligodendrocyte', 'Schwann',
      'Ganglion', 'Nucleus', 'Soma', 'Terminal', 'Vesicle', 'Neuropeptide', 'Hormone', 'Cortisol',
      'Adrenaline', 'Oxytocin', 'Endorphin', 'Melatonin', 'Circadian', 'Rhythm', 'Sleep', 'Wakefulness',
      'Consciousness', 'Awareness', 'Alertness', 'Fatigue', 'Reward', 'Motivation', 'Pleasure', 'Craving',
      'Addiction', 'Tolerance', 'Withdrawal', 'Dependence', 'Circuitry', 'Lobe', 'Frontal', 'Parietal',
      'Temporal', 'Occipital', 'Prefrontal', 'Limbic', 'Basal', 'Ganglia', 'Striatum', 'Putamen',
      'Caudate', 'Substantia', 'Nigra', 'Cerebrospinal', 'Ventricle', 'Meninges', 'Bloodbrain', 'Barrier',
      'Vasculature', 'Perfusion', 'Metabolism', 'Glucose', 'Oxygenation', 'Imaging', 'Scan', 'Electrode',
      'Electroencephalogram', 'Magnetoencephalography', 'Stimulation', 'Optogenetics', 'Biomarker', 'Genome', 'Epigenetics', 'Heredity',
      'Mutation', 'Expression', 'Transcription', 'Protein', 'Enzyme', 'Signaling', 'Feedback', 'Loop',
      'Oscillation', 'Frequency', 'Wave', 'Alpha', 'Beta', 'Theta', 'Delta', 'Gamma',
      'Synchrony', 'Coherence', 'Integration', 'Segregation', 'Lateralization', 'Hemisphere', 'Corpus', 'Callosum',
      'Commissure', 'Tract', 'Fiber', 'Bundle', 'Innervation', 'Afferent', 'Efferent', 'Motor',
      'Sensory', 'Autonomic', 'Sympathetic', 'Parasympathetic', 'Vagus', 'Reflexive', 'Voluntary', 'Involuntary',
      'Coordination', 'Balance', 'Vestibular', 'Kinesthetic', 'Somatosensory', 'Tactile', 'Nociceptor', 'Mechanoreceptor',
      'Thermoreceptor', 'Photoreceptor', 'Retina', 'Optic', 'Chiasm', 'Visual', 'Auditory', 'Cochlea',
      'Olfactory', 'Gustatory', 'Taste', 'Smell', 'Sight', 'Hearing', 'Touch', 'Nerve',
      'Spinal', 'Peripheral', 'Central', 'Ganglionic', 'Preganglionic', 'Postganglionic', 'Innate', 'Learned',
      'Behavior', 'Emotion', 'Mood', 'Anxiety', 'Fear', 'Stress', 'Resilience', 'Coping',
      'Executive', 'Function', 'Impulsivity', 'Flexibility', 'Reasoning', 'Judgment', 'Decision', 'Planning',
      'Memory', 'Load', 'Capacity', 'Bottleneck', 'Filter', 'Salience', 'Novelty', 'Prediction',
      'Error', 'Expectation', 'Surprise', 'Uncertainty', 'Probability', 'Bayesian', 'Model', 'Representation',
      'Abstraction', 'Symbol', 'Concept', 'Category', 'Schema', 'Framework', 'Association', 'Linkage',
      'Binding', 'Convergence', 'Divergence', 'Specialization', 'Localization', 'Distributed', 'Hierarchical', 'Parallel',
      'Sequential', 'Processing', 'Computation', 'Algorithm', 'Heuristic',
    ],
  },
  {
    id: 'philosophy',
    label: 'Philosophy',
    words: [
      'Metaphysics', 'Epistemology', 'Ethics', 'Ontology', 'Logic', 'Aesthetics', 'Existence', 'Reality',
      'Truth', 'Knowledge', 'Belief', 'Justification', 'Skepticism', 'Rationalism', 'Empiricism', 'Idealism',
      'Materialism', 'Dualism', 'Monism', 'Determinism', 'Freewill', 'Freedom', 'Causation', 'Necessity',
      'Contingency', 'Essence', 'Substance', 'Identity', 'Difference', 'Unity', 'Plurality', 'Universal',
      'Particular', 'Abstract', 'Concrete', 'Absolute', 'Relative', 'Objective', 'Subjective', 'Perception',
      'Consciousness', 'Mind', 'Body', 'Soul', 'Spirit', 'Self', 'Person', 'Agency',
      'Intention', 'Action', 'Virtue', 'Vice', 'Duty', 'Obligation', 'Right', 'Wrong',
      'Good', 'Evil', 'Justice', 'Fairness', 'Equality', 'Liberty', 'Autonomy', 'Consent',
      'Contract', 'Society', 'State', 'Sovereignty', 'Authority', 'Legitimacy', 'Power', 'Governance',
      'Democracy', 'Republic', 'Utopia', 'Ideology', 'Doctrine', 'Dogma', 'Paradigm', 'Worldview',
      'Reason', 'Rationality', 'Intuition', 'Instinct', 'Wisdom', 'Prudence', 'Temperance', 'Courage',
      'Humility', 'Integrity', 'Authenticity', 'Meaning', 'Purpose', 'Value', 'Worth', 'Significance',
      'Nihilism', 'Absurdism', 'Existentialism', 'Phenomenology', 'Structuralism', 'Postmodernism', 'Pragmatism', 'Utilitarianism',
      'Deontology', 'Consequentialism', 'Relativism', 'Absolutism', 'Nominalism', 'Realism', 'Pluralism', 'Holism',
      'Reductionism', 'Emergence', 'Teleology', 'Cosmology', 'Theology', 'Transcendence', 'Immanence', 'Infinity',
      'Eternity', 'Time', 'Space', 'Change', 'Motion', 'Stasis', 'Becoming', 'Being',
      'Nothingness', 'Void', 'Paradox', 'Dilemma', 'Contradiction', 'Antinomy', 'Fallacy', 'Premise',
      'Conclusion', 'Argument', 'Inference', 'Deduction', 'Induction', 'Analogy', 'Syllogism', 'Proposition',
      'Predicate', 'Category', 'Definition', 'Concept', 'Idea', 'Form', 'Archetype', 'Symbol',
      'Metaphor', 'Narrative', 'Discourse', 'Dialectic', 'Synthesis', 'Antithesis', 'Thesis', 'Critique',
      'Analysis', 'Interpretation', 'Hermeneutics', 'Text', 'Context', 'Perspective', 'Bias', 'Assumption',
      'Presupposition', 'Certainty', 'Doubt', 'Faith', 'Revelation', 'Experience', 'Observation', 'Evidence',
      'Proof', 'Verification', 'Falsification', 'Hypothesis', 'Theory', 'Framework', 'Model', 'System',
      'Structure', 'Function', 'Process', 'Relation', 'Property', 'Attribute', 'Quality', 'Quantity',
      'Genus', 'Species', 'Individual', 'Collective', 'Community', 'Solidarity', 'Alienation', 'Estrangement',
      'Recognition', 'Dignity', 'Respect', 'Compassion', 'Empathy', 'Altruism', 'Egoism', 'Hedonism',
      'Stoicism', 'Cynicism', 'Epicureanism', 'Naturalism', 'Humanism', 'Enlightenment', 'Modernity', 'Tradition',
      'Custom', 'Convention', 'Norm', 'Law', 'Rule', 'Principle', 'Maxim', 'Precept',
      'Axiom', 'Postulate', 'Foundation', 'Ground', 'Basis', 'Cause', 'Effect', 'Consequence',
      'End', 'Means', 'Instrument', 'Utility', 'Pleasure', 'Pain', 'Suffering', 'Flourishing',
      'Wellbeing', 'Happiness', 'Contentment', 'Serenity', 'Tranquility', 'Equanimity', 'Detachment', 'Attachment',
      'Desire', 'Aversion', 'Passion', 'Emotion', 'Affect', 'Temperament', 'Character', 'Disposition',
      'Habit', 'Practice', 'Discipline', 'Cultivation', 'Growth', 'Development', 'Transformation', 'Awakening',
      'Insight', 'Clarity', 'Understanding', 'Comprehension',
    ],
  },
  {
    id: 'quantum-physics',
    label: 'Quantum Physics',
    words: [
      'Quantum', 'Particle', 'Wave', 'Photon', 'Electron', 'Proton', 'Neutron', 'Boson',
      'Fermion', 'Quark', 'Lepton', 'Antimatter', 'Positron', 'Neutrino', 'Gluon', 'Field',
      'Superposition', 'Entanglement', 'Coherence', 'Decoherence', 'Interference', 'Diffraction', 'Amplitude', 'Frequency',
      'Wavelength', 'Spectrum', 'Spin', 'Charge', 'Mass', 'Energy', 'Momentum', 'Velocity',
      'Acceleration', 'Force', 'Gravity', 'Uncertainty', 'Probability', 'Wavefunction', 'Collapse', 'Observer',
      'Measurement', 'State', 'Eigenstate', 'Eigenvalue', 'Operator', 'Observable', 'Hamiltonian', 'Schrodinger',
      'Equation', 'Orbital', 'Shell', 'Nucleus', 'Isotope', 'Radioactivity', 'Decay', 'Halflife',
      'Fission', 'Fusion', 'Reactor', 'Accelerator', 'Collider', 'Detector', 'Vacuum', 'Void',
      'Spacetime', 'Curvature', 'Dimension', 'Symmetry', 'Invariance', 'Conservation', 'Duality', 'Complementarity',
      'Tunneling', 'Barrier', 'Potential', 'Well', 'Excitation', 'Ground', 'Emission', 'Absorption',
      'Fluorescence', 'Phosphorescence', 'Luminescence', 'Polarization', 'Refraction', 'Reflection', 'Transmission', 'Attenuation',
      'Scattering', 'Diffusion', 'Radiation', 'Blackbody', 'Thermal', 'Statistical', 'Ensemble', 'Entropy',
      'Enthalpy', 'Thermodynamics', 'Equilibrium', 'Phase', 'Transition', 'Condensate', 'Superfluid', 'Superconductor',
      'Semiconductor', 'Insulator', 'Conductor', 'Lattice', 'Crystal', 'Structure', 'Bond', 'Molecule',
      'Atom', 'Compound', 'Element', 'Ion', 'Plasma', 'Gas', 'Liquid', 'Solid',
      'Matter', 'Darkmatter', 'Darkenergy', 'Cosmology', 'Universe', 'Multiverse', 'Singularity', 'Blackhole',
      'Horizon', 'Wormhole', 'Relativity', 'Gravitation', 'Inertia', 'Reference', 'Frame', 'Simultaneity',
      'Dilation', 'Contraction', 'Invariant', 'Lorentz', 'Transformation', 'Fieldtheory', 'Gauge', 'Interaction',
      'Coupling', 'Constant', 'Cross', 'Section', 'Annihilation', 'Creation', 'Fluctuation', 'Virtual',
      'Realparticle', 'Propagator', 'Diagram', 'Renormalization', 'Divergence', 'Regularization', 'Perturbation', 'Approximation',
      'Model', 'Standard', 'Unification', 'Grandunified', 'Theory', 'Stringtheory', 'Superstring', 'Brane',
      'Compactification', 'Extradimension', 'Holography', 'Information', 'Complexity', 'Computation', 'Algorithm', 'Qubit',
      'Gate', 'Circuit', 'Register', 'Errorcorrection', 'Cryptography', 'Teleportation', 'Nonlocality', 'Bellinequality',
      'Hiddenvariable', 'Realism', 'Locality', 'Causality', 'Determinism', 'Indeterminism', 'Randomness', 'Chance',
      'Instability', 'Chaos', 'Order', 'Pattern', 'Breaking', 'Critical', 'Point', 'Scaling',
      'Universality', 'Group', 'Flow', 'Fixed', 'Attractor', 'Bifurcation', 'Nonlinear', 'Dynamics',
      'System', 'Feedback', 'Emergence', 'Selforganization', 'Network', 'Topology', 'Geometry', 'Manifold',
      'Metric', 'Tensor', 'Vector', 'Scalar', 'Gradient', 'Curl', 'Flux', 'Density',
      'Current', 'Continuity', 'Boundary', 'Condition', 'Constraint', 'Degree', 'Freedom', 'Configuration',
      'Space', 'Phasespace', 'Trajectory', 'Orbit', 'Period', 'Oscillation', 'Resonance', 'Damping',
      'Mode', 'Harmonic', 'Overtone', 'Wavicle', 'Bellstate', 'Superconductivity', 'Cryogenics', 'Isospin',
      'Chirality', 'Parity', 'Antiparticle', 'Baryon', 'Meson', 'Hadron', 'Quarkgluon', 'Confinement',
      'Asymptotic', 'Renormalizable', 'Anomaly', 'Instanton', 'Soliton', 'Kink', 'Domainwall',
    ],
  },
  {
    id: 'emotional-mastery',
    label: 'Emotional Mastery',
    words: [
      'Emotion', 'Feeling', 'Mood', 'Affect', 'Sentiment', 'Passion', 'Temperament', 'Disposition',
      'Empathy', 'Compassion', 'Sympathy', 'Kindness', 'Warmth', 'Tenderness', 'Gratitude', 'Appreciation',
      'Contentment', 'Joy', 'Delight', 'Happiness', 'Elation', 'Excitement', 'Enthusiasm', 'Optimism',
      'Hope', 'Confidence', 'Assurance', 'Security', 'Comfort', 'Ease', 'Calm', 'Serenity',
      'Peace', 'Tranquility', 'Stillness', 'Equanimity', 'Balance', 'Stability', 'Grounding', 'Centering',
      'Awareness', 'Mindfulness', 'Presence', 'Attention', 'Focus', 'Clarity', 'Insight', 'Reflection',
      'Introspection', 'Selfawareness', 'Regulation', 'Selfregulation', 'Control', 'Restraint', 'Discipline', 'Patience',
      'Tolerance', 'Acceptance', 'Surrender', 'Letting', 'Release', 'Forgiveness', 'Reconciliation', 'Healing',
      'Recovery', 'Resilience', 'Strength', 'Fortitude', 'Courage', 'Bravery', 'Vulnerability', 'Openness',
      'Honesty', 'Authenticity', 'Sincerity', 'Trust', 'Faith', 'Belief', 'Conviction', 'Determination',
      'Persistence', 'Perseverance', 'Grit', 'Willpower', 'Motivation', 'Drive', 'Ambition', 'Aspiration',
      'Purpose', 'Meaning', 'Fulfillment', 'Satisfaction', 'Pride', 'Selfesteem', 'Selfworth', 'Selfrespect',
      'Dignity', 'Honor', 'Integrity', 'Character', 'Virtue', 'Wisdom', 'Maturity', 'Growth',
      'Development', 'Evolution', 'Transformation', 'Change', 'Adaptation', 'Flexibility', 'Agility', 'Responsiveness',
      'Sensitivity', 'Perceptiveness', 'Intuition', 'Instinct', 'Discernment', 'Judgment', 'Perspective', 'Understanding',
      'Comprehension', 'Recognition', 'Acknowledgment', 'Validation', 'Support', 'Encouragement', 'Affirmation', 'Reassurance',
      'Solace', 'Consolation', 'Relief', 'Catharsis', 'Purification', 'Cleansing', 'Renewal', 'Restoration',
      'Rejuvenation', 'Revitalization', 'Energy', 'Vitality', 'Vigor', 'Zest', 'Fervor', 'Intensity',
      'Depth', 'Richness', 'Fullness', 'Wholeness', 'Completeness', 'Harmony', 'Coherence', 'Alignment',
      'Integration', 'Unity', 'Connection', 'Belonging', 'Intimacy', 'Closeness', 'Bonding', 'Attachment',
      'Affection', 'Love', 'Devotion', 'Loyalty', 'Commitment', 'Dedication', 'Care', 'Nurturing',
      'Generosity', 'Giving', 'Sharing', 'Altruism', 'Selflessness', 'Humility', 'Modesty', 'Grace',
      'Elegance', 'Poise', 'Composure', 'Steadiness', 'Consistency', 'Reliability', 'Dependability', 'Anchoring',
      'Rootedness', 'Settledness', 'Rest', 'Restfulness', 'Relaxation', 'Unwinding', 'Decompression', 'Regeneration',
      'Refreshment', 'Recharge', 'Anger', 'Frustration', 'Irritation', 'Annoyance', 'Resentment', 'Bitterness',
      'Grief', 'Sorrow', 'Sadness', 'Melancholy', 'Loneliness', 'Isolation', 'Anxiety', 'Worry',
      'Nervousness', 'Apprehension', 'Fear', 'Dread', 'Panic', 'Shame', 'Guilt', 'Regret',
      'Remorse', 'Embarrassment', 'Insecurity', 'Doubt', 'Uncertainty', 'Confusion', 'Overwhelm', 'Exhaustion',
      'Burnout', 'Stress', 'Tension', 'Pressure', 'Strain', 'Struggle', 'Conflict', 'Turmoil',
      'Distress', 'Suffering', 'Pain', 'Hurt', 'Wound', 'Trauma', 'Scar', 'Repair',
      'Mending', 'Groundedness', 'Mastery', 'Command', 'Sovereignty', 'Autonomy', 'Independence', 'Freedom',
      'Gratefulness', 'Cheerfulness', 'Buoyancy', 'Levity', 'Lightheartedness',
    ],
  },
  {
    id: 'astronomy-cosmology',
    label: 'Astronomy & Cosmology',
    words: [
      'Galaxy', 'Nebula', 'Supernova', 'Pulsar', 'Quasar', 'Blackhole', 'Wormhole', 'Comet',
      'Asteroid', 'Meteor', 'Meteorite', 'Planet', 'Moon', 'Satellite', 'Orbit', 'Rotation',
      'Revolution', 'Axis', 'Tilt', 'Eclipse', 'Solstice', 'Equinox', 'Constellation', 'Zodiac',
      'Star', 'Sun', 'Solar', 'Lunar', 'Cosmic', 'Universe', 'Multiverse', 'Cosmos',
      'Spacetime', 'Expansion', 'Inflation', 'Bigbang', 'Singularity', 'Horizon', 'Redshift', 'Blueshift',
      'Doppler', 'Parallax', 'Magnitude', 'Luminosity', 'Brightness', 'Spectrum', 'Spectroscopy', 'Telescope',
      'Observatory', 'Radiotelescope', 'Interferometer', 'Probe', 'Spacecraft', 'Mission', 'Launch', 'Trajectory',
      'Gravity', 'Gravitation', 'Mass', 'Density', 'Composition', 'Atmosphere', 'Exosphere', 'Ionosphere',
      'Magnetosphere', 'Aurora', 'Radiation', 'Cosmicray', 'Solarwind', 'Heliosphere', 'Corona', 'Chromosphere',
      'Photosphere', 'Sunspot', 'Flare', 'Prominence', 'Plasma', 'Fusion', 'Nucleosynthesis', 'Element',
      'Hydrogen', 'Helium', 'Carbon', 'Oxygen', 'Nitrogen', 'Iron', 'Silicate', 'Rock',
      'Ice', 'Dust', 'Gas', 'Cloud', 'Disk', 'Accretion', 'Formation', 'Protostar',
      'Protoplanet', 'Planetesimal', 'Debris', 'Belt', 'Ring', 'Crater', 'Surface', 'Terrain',
      'Geology', 'Volcanism', 'Tectonics', 'Habitability', 'Biosignature', 'Exoplanet', 'Exomoon', 'System',
      'Binary', 'Trinary', 'Cluster', 'Supercluster', 'Filament', 'Void', 'Web', 'Structure',
      'Distribution', 'Darkmatter', 'Darkenergy', 'Baryonic', 'Nonbaryonic', 'Curvature', 'Geometry', 'Topology',
      'Flatness', 'Openuniverse', 'Closeduniverse', 'Fate', 'Heatdeath', 'Bigcrunch', 'Bigrip', 'Entropy',
      'Thermodynamics', 'Equilibrium', 'Distance', 'Parsec', 'Lightyear', 'Astronomicalunit', 'Scale', 'Measurement',
      'Calibration', 'Standardcandle', 'Cepheid', 'Variable', 'Binarystar', 'Eclipsingbinary', 'Transit', 'Occultation',
      'Conjunction', 'Opposition', 'Perihelion', 'Aphelion', 'Perigee', 'Apogee', 'Ellipse', 'Eccentricity',
      'Inclination', 'Precession', 'Nutation', 'Libration', 'Tidal', 'Locking', 'Resonance', 'Perturbation',
      'Stability', 'Chaos', 'Dynamics', 'Mechanics', 'Kepler', 'Newton', 'Einstein', 'Relativity',
      'Lensing', 'Gravitationallens', 'Microlensing', 'Cosmicmicrowave', 'Background', 'Anisotropy', 'Fluctuation', 'Inflationary',
      'Epoch', 'Recombination', 'Reionization', 'Darkage', 'Firststars', 'Population', 'Metallicity', 'Isotope',
      'Halflife', 'Decay', 'Interstellar', 'Intergalactic', 'Medium', 'Molecularcloud', 'Starformation', 'Stellarnursery',
      'Ionization', 'Emission', 'Absorption', 'Line', 'Spectralclass', 'Temperature', 'Colorindex', 'Hertzsprung',
      'Russell', 'Diagram', 'Mainsequence', 'Giant', 'Dwarf', 'Whitedwarf', 'Neutronstar', 'Magnetar',
      'Remnant', 'Shell', 'Shockwave', 'Ejecta', 'Enrichment', 'Recycling', 'Lifecycle', 'Birth',
      'Death', 'Collapse', 'Explosion', 'Detonation', 'Energy', 'Output', 'Reaction', 'Chain',
      'Process', 'Protonproton', 'Cnocycle', 'TripleAlpha', 'Silicon', 'Burning', 'Corecollapse', 'Chandrasekhar',
      'Limit', 'Escapevelocity', 'Eventhorizon', 'Spaghettification', 'Hawking', 'Informationparadox', 'Firewall', 'Ergosphere',
      'Zenith', 'Nadir', 'Meridian', 'Culmination', 'Syzygy',
    ],
  },
  {
    id: 'ancient-mythology',
    label: 'Ancient Mythology',
    words: [
      'Myth', 'Legend', 'Saga', 'Epic', 'Folklore', 'Oracle', 'Prophecy', 'Omen',
      'Ritual', 'Sacrifice', 'Offering', 'Shrine', 'Temple', 'Altar', 'Sanctuary', 'Pantheon',
      'Deity', 'Divinity', 'Godhead', 'Immortal', 'Mortal', 'Demigod', 'Titan', 'Giant',
      'Nymph', 'Spirit', 'Ghost', 'Phantom', 'Specter', 'Wraith', 'Underworld', 'Afterlife',
      'Heaven', 'Paradise', 'Elysium', 'Abyss', 'Chaos', 'Cosmos', 'Creation', 'Genesis',
      'Origin', 'Ancestor', 'Lineage', 'Dynasty', 'Bloodline', 'Heritage', 'Legacy', 'Kingdom',
      'Empire', 'Realm', 'Throne', 'Crown', 'Scepter', 'Chariot', 'Trident', 'Thunderbolt',
      'Lightning', 'Storm', 'Tempest', 'Whirlwind', 'Flood', 'Deluge', 'Serpent', 'Dragon',
      'Phoenix', 'Griffin', 'Sphinx', 'Chimera', 'Hydra', 'Cerberus', 'Minotaur', 'Centaur',
      'Satyr', 'Faun', 'Siren', 'Mermaid', 'Kraken', 'Leviathan', 'Behemoth', 'Colossus',
      'Labyrinth', 'Maze', 'Quest', 'Journey', 'Odyssey', 'Voyage', 'Pilgrimage', 'Trial',
      'Ordeal', 'Challenge', 'Riddle', 'Curse', 'Blessing', 'Charm', 'Amulet', 'Talisman',
      'Relic', 'Artifact', 'Treasure', 'Vessel', 'Cauldron', 'Chalice', 'Grail', 'Sword',
      'Shield', 'Armor', 'Spear', 'Bow', 'Arrow', 'Blade', 'Warrior', 'Hero',
      'Champion', 'Guardian', 'Protector', 'Sentinel', 'Herald', 'Messenger', 'Emissary', 'Envoy',
      'Priest', 'Priestess', 'Seer', 'Sage', 'Prophet', 'Mystic', 'Sorcerer', 'Sorceress',
      'Witch', 'Wizard', 'Enchanter', 'Magician', 'Spell', 'Incantation', 'Chant', 'Hymn',
      'Invocation', 'Summoning', 'Conjuring', 'Transformation', 'Metamorphosis', 'Shapeshifter', 'Trickster', 'Jester',
      'Fool', 'Wanderer', 'Nomad', 'Exile', 'Outcast', 'Fugitive', 'Betrayal', 'Vengeance',
      'Retribution', 'Justice', 'Fate', 'Destiny', 'Providence', 'Doom', 'Judgment', 'Reckoning',
      'Redemption', 'Salvation', 'Deliverance', 'Rebirth', 'Resurrection', 'Ascension', 'Descent', 'Fall',
      'Rise', 'Triumph', 'Glory', 'Honor', 'Valor', 'Courage', 'Bravery', 'Nobility',
      'Sovereignty', 'Majesty', 'Grandeur', 'Splendor', 'Radiance', 'Luminance', 'Brilliance', 'Darkness',
      'Shadow', 'Twilight', 'Dawn', 'Dusk', 'Eternity', 'Infinity', 'Everlasting', 'Timeless',
      'Ageless', 'Primordial', 'Ancient', 'Archaic', 'Elder', 'Forebear', 'Progenitor', 'Keeper',
      'Watcher', 'Overseer', 'Ruler', 'Sovereign', 'Monarch', 'Emperor', 'Empress', 'Regent',
      'Consort', 'Betrothed', 'Bride', 'Groom', 'Union', 'Marriage', 'Covenant', 'Pact',
      'Alliance', 'Bond', 'Oath', 'Vow', 'Promise', 'Pledge', 'Loyalty', 'Fealty',
      'Allegiance', 'Devotion', 'Worship', 'Veneration', 'Reverence', 'Adoration', 'Piety', 'Faith',
      'Belief', 'Tradition', 'Custom', 'Rite', 'Ceremony', 'Festival', 'Celebration', 'Feast',
      'Banquet', 'Procession', 'Grove', 'Forest', 'Mountain', 'River', 'Ocean', 'Sea',
      'Wind', 'Fire', 'Earth', 'Water', 'Element', 'Force', 'Power', 'Energy',
    ],
  },
  {
    id: 'architecture-design',
    label: 'Architecture & Design',
    words: [
      'Structure', 'Foundation', 'Framework', 'Facade', 'Column', 'Pillar', 'Beam', 'Truss',
      'Arch', 'Vault', 'Dome', 'Spire', 'Tower', 'Turret', 'Buttress', 'Cornice',
      'Pediment', 'Capital', 'Frieze', 'Balustrade', 'Colonnade', 'Portico', 'Atrium', 'Courtyard',
      'Plaza', 'Terrace', 'Balcony', 'Veranda', 'Loggia', 'Gallery', 'Corridor', 'Threshold',
      'Portal', 'Gateway', 'Entrance', 'Elevation', 'Silhouette', 'Profile', 'Massing', 'Volume',
      'Proportion', 'Scale', 'Symmetry', 'Asymmetry', 'Balance', 'Rhythm', 'Repetition', 'Pattern',
      'Texture', 'Material', 'Concrete', 'Steel', 'Timber', 'Masonry', 'Brick', 'Stone',
      'Marble', 'Granite', 'Glass', 'Ceramic', 'Composite', 'Cladding', 'Insulation', 'Membrane',
      'Panel', 'Grid', 'Module', 'Component', 'Assembly', 'Construction', 'Fabrication', 'Prefabrication',
      'Modular', 'Sustainable', 'Ecological', 'Passive', 'Ventilation', 'Efficiency', 'Orientation', 'Lighting',
      'Daylight', 'Shading', 'Aperture', 'Fenestration', 'Skylight', 'Clerestory', 'Louver', 'Screen',
      'Partition', 'Enclosure', 'Envelope', 'Perimeter', 'Boundary', 'Zoning', 'Planning', 'Layout',
      'Circulation', 'Flow', 'Sequence', 'Transition', 'Spatial', 'Perception', 'Experience', 'Ambiance',
      'Atmosphere', 'Mood', 'Character', 'Identity', 'Context', 'Site', 'Landscape', 'Topography',
      'Terrain', 'Environment', 'Climate', 'Microclimate', 'Ecology', 'Urbanism', 'Cityscape', 'Streetscape',
      'Skyline', 'Density', 'Height', 'Setback', 'Footprint', 'Coverage', 'Ratio', 'Golden',
      'Modulor', 'Axis', 'Vista', 'Sightline', 'Perspective', 'Vanishing', 'Point', 'Composition',
      'Form', 'Function', 'Ornament', 'Decoration', 'Motif', 'Detail', 'Craftsmanship', 'Artisan',
      'Vernacular', 'Classical', 'Gothic', 'Baroque', 'Renaissance', 'Modernist', 'Brutalist', 'Minimalist',
      'Contemporary', 'Postmodern', 'Deconstructivist', 'Organic', 'Biomorphic', 'Parametric', 'Digital', 'Prototype',
      'Model', 'Rendering', 'Drawing', 'Sketch', 'Blueprint', 'Plan', 'Section', 'Specification',
      'Schedule', 'Documentation', 'Permit', 'Code', 'Regulation', 'Standard', 'Compliance', 'Safety',
      'Egress', 'Accessibility', 'Universal', 'Design', 'Ergonomics', 'Anthropometry', 'Human', 'Comfort',
      'Wellbeing', 'Occupant', 'User', 'Interaction', 'Interface', 'Furniture', 'Fixture', 'Fitting',
      'Finish', 'Surface', 'Color', 'Palette', 'Hue', 'Tone', 'Contrast', 'Harmony',
      'Arrangement', 'Configuration', 'Adjacency', 'Proximity', 'Hierarchy', 'Emphasis', 'Focal', 'Landmark',
      'Monument', 'Icon', 'Symbol', 'Meaning', 'Narrative', 'Concept', 'Vision', 'Innovation',
      'Technology', 'Engineering', 'Structural', 'System', 'Mechanical', 'Electrical', 'Plumbing', 'Infrastructure',
      'Utility', 'Sustainability', 'Resilience', 'Adaptability', 'Flexibility', 'Longevity', 'Durability', 'Maintenance',
      'Renovation', 'Restoration', 'Preservation', 'Heritage', 'Conservation', 'Adaptive', 'Reuse', 'Retrofit',
      'Upgrade', 'Transformation', 'Revitalization', 'Regeneration', 'Renewal', 'Vestibule', 'Anteroom', 'Mezzanine',
      'Parapet', 'Soffit',
    ],
  },
  {
    id: 'music-theory',
    label: 'Music Theory',
    words: [
      'Melody', 'Harmony', 'Rhythm', 'Tempo', 'Meter', 'Beat', 'Pulse', 'Cadence',
      'Phrase', 'Motif', 'Theme', 'Variation', 'Development', 'Progression', 'Chord', 'Interval',
      'Scale', 'Mode', 'Key', 'Tonality', 'Modulation', 'Transposition', 'Pitch', 'Note',
      'Octave', 'Semitone', 'Tone', 'Timbre', 'Texture', 'Dynamics', 'Crescendo', 'Diminuendo',
      'Forte', 'Piano', 'Staccato', 'Legato', 'Accent', 'Syncopation', 'Polyrhythm', 'Counterpoint',
      'Polyphony', 'Homophony', 'Monophony', 'Unison', 'Consonance', 'Dissonance', 'Resolution', 'Suspension',
      'Tension', 'Release', 'Composition', 'Arrangement', 'Orchestration', 'Instrumentation', 'Score', 'Notation',
      'Staff', 'Clef', 'Signature', 'Bar', 'Measure', 'Rest', 'Sustain', 'Articulation',
      'Phrasing', 'Expression', 'Interpretation', 'Performance', 'Improvisation', 'Ensemble', 'Orchestra', 'Symphony',
      'Concerto', 'Sonata', 'Suite', 'Overture', 'Prelude', 'Fugue', 'Canon', 'Rondo',
      'Aria', 'Recitative', 'Chorus', 'Refrain', 'Verse', 'Bridge', 'Coda', 'Introduction',
      'Exposition', 'Recapitulation', 'Movement', 'Section', 'Passage', 'Fragment', 'Sequence', 'Pattern',
      'Figure', 'Ornament', 'Embellishment', 'Trill', 'Vibrato', 'Tremolo', 'Glissando', 'Portamento',
      'Fermata', 'Ritardando', 'Accelerando', 'Rubato', 'Register', 'Range', 'Tessitura', 'Resonance',
      'Overtone', 'Harmonic', 'Fundamental', 'Frequency', 'Amplitude', 'Waveform', 'Vibration', 'Acoustics',
      'Reverberation', 'Echo', 'Decay', 'Attack', 'Envelope', 'Filter', 'Synthesis', 'Sampling',
      'Sequencing', 'Recording', 'Production', 'Mixing', 'Mastering', 'Amplification', 'Distortion', 'Reverb',
      'Delay', 'Compression', 'Equalization', 'Spectrum', 'Instrument', 'String', 'Woodwind', 'Brass',
      'Percussion', 'Keyboard', 'Vocal', 'Choir', 'Soloist', 'Accompaniment', 'Conductor', 'Baton',
      'Podium', 'Genre', 'Style', 'Tradition', 'Culture', 'Folk', 'Classical', 'Baroque',
      'Romantic', 'Contemporary', 'Experimental', 'Improvisational', 'Jazz', 'Blues', 'Swing', 'Bebop',
      'Fusion', 'Minimalism', 'Serialism', 'Atonality', 'Chromaticism', 'Diatonic', 'Pentatonic', 'Modal',
      'Tonal', 'Cadential', 'Functional', 'Circle', 'Fifths', 'Root', 'Third', 'Fifth',
      'Seventh', 'Ninth', 'Extension', 'Inversion', 'Voicing', 'Voice', 'Leading', 'Species',
      'Imitation', 'Augmentation', 'Diminution', 'Retrograde', 'Transformation', 'Cell', 'Gesture', 'Contour',
      'Shape', 'Direction', 'Motion', 'Stepwise', 'Leap', 'Consonant', 'Dissonant', 'Stable',
      'Unstable', 'Anticipation', 'Appoggiatura', 'Passing', 'Neighbor', 'Escape', 'Pedal', 'Drone',
      'Ostinato', 'Riff', 'Groove', 'Feel', 'Shuffle', 'Straight', 'Triplet', 'Sixteenth',
      'Eighth', 'Quarter', 'Half', 'Whole', 'Sightreading', 'Earsound', 'Solfege', 'Absolute',
      'Relative', 'Perfect', 'Intonation', 'Tuning', 'Backbeat', 'Downbeat', 'Upbeat', 'Anacrusis',
      'Hemiola', 'Polymeter', 'Vamp', 'Turnaround', 'Cadenza', 'Segue', 'Countermelody', 'Descant',
      'Ritenuto', 'Tacet', 'Divisi',
    ],
  },
  {
    id: 'economics-finance',
    label: 'Economics & Finance',
    words: [
      'Market', 'Economy', 'Capital', 'Asset', 'Liability', 'Equity', 'Debt', 'Credit',
      'Interest', 'Inflation', 'Deflation', 'Recession', 'Depression', 'Recovery', 'Expansion', 'Contraction',
      'Cycle', 'Growth', 'Output', 'Productivity', 'Efficiency', 'Supply', 'Demand', 'Equilibrium',
      'Surplus', 'Deficit', 'Scarcity', 'Abundance', 'Allocation', 'Distribution', 'Investment', 'Portfolio',
      'Diversification', 'Hedge', 'Derivative', 'Option', 'Future', 'Bond', 'Stock', 'Share',
      'Dividend', 'Yield', 'Return', 'Risk', 'Volatility', 'Liquidity', 'Solvency', 'Leverage',
      'Margin', 'Collateral', 'Mortgage', 'Loan', 'Lending', 'Borrowing', 'Savings', 'Consumption',
      'Spending', 'Budget', 'Fiscal', 'Monetary', 'Policy', 'Regulation', 'Taxation', 'Subsidy',
      'Tariff', 'Trade', 'Export', 'Import', 'Currency', 'Exchange', 'Rate', 'Valuation',
      'Appreciation', 'Depreciation', 'Devaluation', 'Revaluation', 'Reserve', 'Bank', 'Central', 'Commercial',
      'Institution', 'Intermediary', 'Broker', 'Dealer', 'Index', 'Benchmark', 'Sector', 'Industry',
      'Corporation', 'Enterprise', 'Startup', 'Venture', 'Entrepreneur', 'Innovation', 'Competition', 'Monopoly',
      'Oligopoly', 'Cartel', 'Antitrust', 'Compliance', 'Governance', 'Stakeholder', 'Shareholder', 'Earnings',
      'Revenue', 'Profit', 'Cost', 'Expense', 'Overhead', 'Amortization', 'Appraisal', 'Assessment',
      'Audit', 'Accounting', 'Bookkeeping', 'Ledger', 'Balance', 'Statement', 'Cashflow', 'Income',
      'Expenditure', 'Budgeting', 'Forecasting', 'Projection', 'Analysis', 'Modeling', 'Simulation', 'Scenario',
      'Sensitivity', 'Optimization', 'Utility', 'Preference', 'Rational', 'Behavioral', 'Bias', 'Heuristic',
      'Incentive', 'Motivation', 'Reward', 'Penalty', 'Externality', 'Publicgood', 'Commonresource', 'Freerider',
      'Moralhazard', 'Adverseselection', 'Asymmetry', 'Information', 'Signaling', 'Screening', 'Negotiation', 'Bargaining',
      'Contract', 'Agreement', 'Transaction', 'Barter', 'Commodity', 'Resource', 'Labor', 'Wage',
      'Employment', 'Unemployment', 'Workforce', 'Specialization', 'Division', 'Comparative', 'Advantage', 'Globalization',
      'Protectionism', 'Freetrade', 'Quota', 'Embargo', 'Sanction', 'Development', 'Emerging', 'Developed',
      'Infrastructure', 'Capitalformation', 'Savingsrate', 'Multiplier', 'Accelerator', 'Businesscycle', 'Boom', 'Bust',
      'Bubble', 'Crash', 'Correction', 'Rally', 'Bear', 'Bull', 'Sentiment', 'Confidence',
      'Speculation', 'Arbitrage', 'Insurance', 'Premium', 'Actuarial', 'Underwriting', 'Claim', 'Coverage',
      'Deductible', 'Retirement', 'Pension', 'Annuity', 'Fund', 'Endowment', 'Trust', 'Estate',
      'Inheritance', 'Wealth', 'Networth', 'Bankruptcy', 'Insolvency', 'Liquidation', 'Restructuring', 'Merger',
      'Acquisition', 'Consolidation', 'Divestiture', 'Synergy', 'Multiple', 'Ratio', 'Metric', 'Indicator',
      'Performance', 'Input', 'Technology', 'Disruption', 'Transformation', 'Marginal', 'Elasticity', 'Substitute',
      'Complement', 'Deadweight', 'Loss', 'Rent', 'Seeking', 'Asymmetric', 'Principal', 'Agent',
      'Fiduciary', 'Custodian', 'Underwriter', 'Syndication', 'Securitization', 'Tranching', 'Capitalization', 'Discounting',
      'Bailment', 'Fungibility',
    ],
  },
  {
    id: 'marine-biology',
    label: 'Marine Biology',
    words: [
      'Ocean', 'Sea', 'Reef', 'Coral', 'Coastline', 'Shoreline', 'Tide', 'Current',
      'Wave', 'Surf', 'Depth', 'Trench', 'Abyss', 'Seafloor', 'Sediment', 'Plankton',
      'Phytoplankton', 'Zooplankton', 'Algae', 'Kelp', 'Seagrass', 'Mangrove', 'Estuary', 'Lagoon',
      'Atoll', 'Archipelago', 'Habitat', 'Ecosystem', 'Biodiversity', 'Species', 'Organism', 'Fish',
      'Shark', 'Ray', 'Whale', 'Dolphin', 'Porpoise', 'Seal', 'Walrus', 'Otter',
      'Turtle', 'Crustacean', 'Crab', 'Lobster', 'Shrimp', 'Mollusk', 'Squid', 'Octopus',
      'Cuttlefish', 'Nautilus', 'Jellyfish', 'Anemone', 'Starfish', 'Urchin', 'Sponge', 'Barnacle',
      'Mussel', 'Clam', 'Oyster', 'Scallop', 'Predator', 'Prey', 'Foodweb', 'Foodchain',
      'Symbiosis', 'Mutualism', 'Parasitism', 'Commensalism', 'Camouflage', 'Mimicry', 'Bioluminescence', 'Migration',
      'Spawning', 'Breeding', 'Reproduction', 'Larva', 'Juvenile', 'Adult', 'Lifecycle', 'Population',
      'Colony', 'School', 'Pod', 'Shoal', 'Territory', 'Range', 'Distribution', 'Adaptation',
      'Evolution', 'Speciation', 'Extinction', 'Conservation', 'Sanctuary', 'Reserve', 'Protection', 'Restoration',
      'Rehabilitation', 'Monitoring', 'Survey', 'Census', 'Sampling', 'Tagging', 'Tracking', 'Telemetry',
      'Sonar', 'Echolocation', 'Navigation', 'Buoyancy', 'Pressure', 'Salinity', 'Temperature', 'Thermocline',
      'Halocline', 'Upwelling', 'Downwelling', 'Circulation', 'Gyre', 'Vortex', 'Turbulence', 'Stratification',
      'Layer', 'Zone', 'Photic', 'Aphotic', 'Twilight', 'Midnight', 'Benthic', 'Pelagic',
      'Neritic', 'Oceanic', 'Intertidal', 'Subtidal', 'Continental', 'Shelf', 'Slope', 'Rise',
      'Basin', 'Ridge', 'Seamount', 'Volcano', 'Hydrothermal', 'Vent', 'Chemosynthesis', 'Photosynthesis',
      'Productivity', 'Nutrient', 'Cycling', 'Decomposition', 'Detritus', 'Carbon', 'Sequestration', 'Acidification',
      'Bleaching', 'Warming', 'Pollution', 'Contamination', 'Debris', 'Microplastic', 'Runoff', 'Eutrophication',
      'Overfishing', 'Bycatch', 'Trawling', 'Aquaculture', 'Fishery', 'Stock', 'Sustainability', 'Yield',
      'Harvest', 'Quota', 'Regulation', 'Management', 'Policy', 'Treaty', 'Convention', 'Jurisdiction',
      'Territorial', 'International', 'Exclusive', 'Economic', 'Boundary', 'Baseline', 'Delimitation', 'Sovereignty',
      'Resource', 'Extraction', 'Mining', 'Drilling', 'Exploration', 'Expedition', 'Research', 'Vessel',
      'Submersible', 'Submarine', 'Diving', 'Snorkeling', 'Scuba', 'Equipment', 'Instrument', 'Sensor',
      'Buoy', 'Satellite', 'Imaging', 'Mapping', 'Bathymetry', 'Topography', 'Geomorphology', 'Sedimentology',
      'Stratigraphy', 'Core', 'Sample', 'Analysis', 'Data', 'Model', 'Simulation', 'Prediction',
      'Forecast', 'Climate', 'Weather', 'Storm', 'Hurricane', 'Cyclone', 'Typhoon', 'Swell',
      'Wavelength', 'Amplitude', 'Frequency', 'Erosion', 'Deposition', 'Accretion', 'Transport', 'Formation',
      'Geology', 'Mineral', 'Composition', 'Structure', 'Texture', 'Color', 'Pattern', 'Density',
      'Diversity', 'Abundance', 'Richness', 'Evenness', 'Dominance', 'Rarity', 'Endemic', 'Native',
      'Invasive', 'Introduced', 'Nonnative', 'Alien', 'Threatened', 'Endangered', 'Vulnerable', 'Resilient',
    ],
  },
  {
    id: 'botany-plant-life',
    label: 'Botany & Plant Life',
    words: [
      'Plant', 'Flower', 'Blossom', 'Petal', 'Sepal', 'Stamen', 'Pistil', 'Pollen',
      'Nectar', 'Fragrance', 'Leaf', 'Stem', 'Root', 'Branch', 'Trunk', 'Bark',
      'Canopy', 'Foliage', 'Frond', 'Blade', 'Vein', 'Chlorophyll', 'Photosynthesis', 'Respiration',
      'Transpiration', 'Osmosis', 'Absorption', 'Growth', 'Germination', 'Seed', 'Sprout', 'Seedling',
      'Sapling', 'Cutting', 'Graft', 'Propagation', 'Pollination', 'Fertilization', 'Reproduction', 'Fruit',
      'Berry', 'Nut', 'Pod', 'Grain', 'Kernel', 'Husk', 'Shell', 'Rind',
      'Peel', 'Pulp', 'Juice', 'Sap', 'Resin', 'Latex', 'Oil', 'Wax',
      'Fiber', 'Cellulose', 'Lignin', 'Tissue', 'Cell', 'Wall', 'Membrane', 'Nucleus',
      'Chloroplast', 'Vacuole', 'Cytoplasm', 'Meristem', 'Cambium', 'Xylem', 'Phloem', 'Vascular',
      'System', 'Nutrient', 'Mineral', 'Nitrogen', 'Phosphorus', 'Potassium', 'Fertilizer', 'Compost',
      'Soil', 'Humus', 'Loam', 'Clay', 'Sand', 'Substrate', 'Drainage', 'Irrigation',
      'Moisture', 'Hydration', 'Climate', 'Season', 'Dormancy', 'Deciduous', 'Evergreen', 'Perennial',
      'Annual', 'Biennial', 'Hardy', 'Tender', 'Species', 'Genus', 'Family', 'Classification',
      'Taxonomy', 'Nomenclature', 'Variety', 'Cultivar', 'Hybrid', 'Strain', 'Adaptation', 'Evolution',
      'Diversity', 'Habitat', 'Ecosystem', 'Biome', 'Forest', 'Woodland', 'Grassland', 'Prairie',
      'Meadow', 'Savanna', 'Desert', 'Tundra', 'Wetland', 'Marsh', 'Swamp', 'Rainforest',
      'Understory', 'Undergrowth', 'Groundcover', 'Vine', 'Creeper', 'Climber', 'Shrub', 'Bush',
      'Hedge', 'Thicket', 'Grove', 'Orchard', 'Garden', 'Nursery', 'Greenhouse', 'Cultivation',
      'Horticulture', 'Agriculture', 'Farming', 'Harvest', 'Yield', 'Crop', 'Rotation', 'Companion',
      'Planting', 'Mulching', 'Pruning', 'Trimming', 'Weeding', 'Pest', 'Disease', 'Fungus',
      'Mold', 'Blight', 'Infestation', 'Resistance', 'Immunity', 'Defense', 'Toxin', 'Alkaloid',
      'Compound', 'Extract', 'Essence', 'Herb', 'Spice', 'Medicine', 'Remedy', 'Healing',
      'Therapeutic', 'Medicinal', 'Aromatic', 'Botanical', 'Herbarium', 'Specimen', 'Collection', 'Identification',
      'Field', 'Guide', 'Survey', 'Inventory', 'Conservation', 'Preservation', 'Restoration', 'Reforestation',
      'Afforestation', 'Deforestation', 'Erosion', 'Degradation', 'Fertility', 'Productivity', 'Biomass', 'Vegetation',
      'Flora', 'Biodiversity', 'Endemism', 'Native', 'Invasive', 'Naturalized', 'Wildflower', 'Weed',
      'Grass', 'Moss', 'Lichen', 'Fern', 'Conifer', 'Broadleaf', 'Hardwood', 'Softwood',
      'Timber', 'Lumber', 'Ring', 'Age', 'Height', 'Girth', 'Spread', 'Shade',
      'Sunlight', 'Exposure', 'Orientation', 'Aspect', 'Elevation', 'Altitude', 'Latitude', 'Zone',
      'Region', 'Range', 'Distribution', 'Migration', 'Dispersal', 'Colonization', 'Succession', 'Pioneer',
      'Climax', 'Community', 'Association', 'Interaction', 'Competition', 'Symbiosis', 'Mycorrhiza', 'Rhizosphere',
      'Microbiome', 'Bacteria', 'Fungi',
    ],
  },
  {
    id: 'geology-earth-science',
    label: 'Geology & Earth Science',
    words: [
      'Rock', 'Mineral', 'Crystal', 'Sediment', 'Stratum', 'Layer', 'Formation', 'Deposit',
      'Erosion', 'Weathering', 'Sedimentation', 'Compaction', 'Cementation', 'Lithification', 'Metamorphism', 'Crystallization',
      'Solidification', 'Cooling', 'Magma', 'Lava', 'Volcano', 'Eruption', 'Crater', 'Caldera',
      'Vent', 'Fissure', 'Fault', 'Fracture', 'Crack', 'Rift', 'Tectonic', 'Plate',
      'Boundary', 'Subduction', 'Collision', 'Divergence', 'Convergence', 'Transform', 'Earthquake', 'Seismic',
      'Tremor', 'Aftershock', 'Epicenter', 'Hypocenter', 'Magnitude', 'Intensity', 'Wave', 'Vibration',
      'Rupture', 'Mountain', 'Range', 'Peak', 'Summit', 'Ridge', 'Valley', 'Canyon',
      'Gorge', 'Plateau', 'Basin', 'Plain', 'Delta', 'Floodplain', 'Terrace', 'Escarpment',
      'Cliff', 'Slope', 'Gradient', 'Elevation', 'Topography', 'Landscape', 'Terrain', 'Relief',
      'Contour', 'Geomorphology', 'Landform', 'Glacier', 'Icecap', 'Iceberg', 'Moraine', 'Crevasse',
      'Fjord', 'Cirque', 'Drumlin', 'Esker', 'Outwash', 'Till', 'Permafrost', 'Tundra',
      'Desert', 'Dune', 'Oasis', 'Aquifer', 'Groundwater', 'Watertable', 'Spring', 'Geyser',
      'Hotspring', 'Fumarole', 'Cave', 'Cavern', 'Karst', 'Sinkhole', 'Stalactite', 'Stalagmite',
      'Limestone', 'Sandstone', 'Shale', 'Granite', 'Basalt', 'Obsidian', 'Pumice', 'Quartz',
      'Feldspar', 'Mica', 'Calcite', 'Gypsum', 'Halite', 'Pyrite', 'Hematite', 'Magnetite',
      'Sulfur', 'Graphite', 'Diamond', 'Gemstone', 'Ore', 'Vein', 'Mining', 'Extraction',
      'Excavation', 'Quarry', 'Fossil', 'Fossilization', 'Preservation', 'Stratigraphy', 'Superposition', 'Correlation',
      'Dating', 'Radiometric', 'Isotope', 'Halflife', 'Decay', 'Chronology', 'Timescale', 'Era',
      'Epoch', 'Period', 'Eon', 'Age', 'Precambrian', 'Paleozoic', 'Mesozoic', 'Cenozoic',
      'Extinction', 'Evolution', 'Adaptation', 'Species', 'Ecosystem', 'Habitat', 'Continental', 'Drift',
      'Pangea', 'Supercontinent', 'Craton', 'Crust', 'Mantle', 'Core', 'Lithosphere', 'Asthenosphere',
      'Mesosphere', 'Convection', 'Circulation', 'Current', 'Density', 'Pressure', 'Temperature', 'Heat',
      'Flow', 'Buoyancy', 'Isostasy', 'Equilibrium', 'Uplift', 'Subsidence', 'Sedimentary', 'Igneous',
      'Metamorphic', 'Cycle', 'Transformation', 'Physical', 'Chemical', 'Biological', 'Transport', 'Deposition',
      'Denudation', 'Degradation', 'Aggradation', 'Alluvium', 'Colluvium', 'Regolith', 'Soil', 'Horizon',
      'Profile', 'Texture', 'Structure', 'Fertility', 'Composition', 'Hydrology', 'Watershed', 'Drainage',
      'Tributary', 'Confluence', 'Meander', 'Oxbow', 'Estuary', 'Load', 'Discharge', 'Velocity',
      'Channel', 'Levee', 'Atmosphere', 'Weather', 'Climate', 'Precipitation', 'Evaporation', 'Condensation',
      'Humidity', 'Wind', 'Front', 'System', 'Cyclone', 'Anticyclone', 'Jetstream', 'Pattern',
      'Season', 'Variation', 'Trend', 'Data', 'Measurement', 'Instrument', 'Survey', 'Mapping',
      'Model', 'Prediction', 'Analysis', 'Research', 'Fieldwork', 'Outcrop', 'Bedrock', 'Overburden',
      'Foliation', 'Anticline', 'Syncline',
    ],
  },
  {
    id: 'mathematics-logic',
    label: 'Mathematics & Logic',
    words: [
      'Number', 'Integer', 'Fraction', 'Decimal', 'Ratio', 'Proportion', 'Percentage', 'Variable',
      'Constant', 'Coefficient', 'Equation', 'Formula', 'Expression', 'Function', 'Graph', 'Curve',
      'Line', 'Slope', 'Intercept', 'Axis', 'Coordinate', 'Plane', 'Dimension', 'Vector',
      'Matrix', 'Determinant', 'Scalar', 'Tensor', 'Transformation', 'Rotation', 'Reflection', 'Translation',
      'Symmetry', 'Congruence', 'Similarity', 'Angle', 'Degree', 'Radian', 'Triangle', 'Polygon',
      'Circle', 'Radius', 'Diameter', 'Circumference', 'Area', 'Volume', 'Perimeter', 'Surface',
      'Geometry', 'Topology', 'Algebra', 'Calculus', 'Derivative', 'Integral', 'Limit', 'Continuity',
      'Convergence', 'Divergence', 'Series', 'Sequence', 'Sum', 'Product', 'Factorial', 'Permutation',
      'Combination', 'Probability', 'Statistics', 'Distribution', 'Mean', 'Median', 'Mode', 'Variance',
      'Deviation', 'Correlation', 'Regression', 'Hypothesis', 'Inference', 'Sampling', 'Population', 'Estimation',
      'Prime', 'Composite', 'Factor', 'Multiple', 'Divisor', 'Remainder', 'Modulus', 'Theorem',
      'Proof', 'Axiom', 'Postulate', 'Lemma', 'Corollary', 'Conjecture', 'Proposition', 'Deduction',
      'Induction', 'Logic', 'Reasoning', 'Argument', 'Premise', 'Conclusion', 'Validity', 'Soundness',
      'Consistency', 'Completeness', 'Decidability', 'Computability', 'Algorithm', 'Recursion', 'Iteration', 'Complexity',
      'Efficiency', 'Optimization', 'Approximation', 'Precision', 'Accuracy', 'Error', 'Set', 'Subset',
      'Union', 'Intersection', 'Complement', 'Element', 'Member', 'Domain', 'Range', 'Mapping',
      'Bijection', 'Injection', 'Surjection', 'Isomorphism', 'Homomorphism', 'Group', 'Ring', 'Field',
      'Space', 'Operator', 'Operation', 'Identity', 'Inverse', 'Associative', 'Commutative', 'Distributive',
      'Closure', 'Structure', 'Property', 'Relation', 'Order', 'Partial', 'Total', 'Equivalence',
      'Class', 'Quotient', 'Partition', 'Lattice', 'Boolean', 'Binary', 'Truth', 'Value',
      'Statement', 'Predicate', 'Quantifier', 'Universal', 'Existential', 'Conditional', 'Biconditional', 'Negation',
      'Conjunction', 'Disjunction', 'Implication', 'Tautology', 'Contradiction', 'Fallacy', 'Paradox', 'Infinity',
      'Finite', 'Countable', 'Uncountable', 'Continuum', 'Cardinality', 'Ordinal', 'Convergent', 'Divergent',
      'Bounded', 'Unbounded', 'Monotonic', 'Increasing', 'Decreasing', 'Extremum', 'Maximum', 'Minimum',
      'Constraint', 'Linear', 'Nonlinear', 'Polynomial', 'Exponential', 'Logarithmic', 'Trigonometric', 'Sine',
      'Cosine', 'Tangent', 'Codomain', 'Continuous', 'Discrete', 'Discontinuous', 'Differentiable', 'Integrable',
      'Analytic', 'Approximate', 'Numerical', 'Method', 'Solution', 'System', 'Model', 'Simulation',
      'Computation', 'Calculation', 'Verification', 'Validation', 'Manifold', 'Metric', 'Distance', 'Norm',
      'Basis', 'Span', 'Rank', 'Nullity', 'Eigenvalue', 'Eigenvector', 'Trace', 'Projection',
      'Orthogonal', 'Perpendicular', 'Parallel', 'Homeomorphism', 'Diffeomorphism', 'Submanifold', 'Cohomology', 'Homology',
      'Fibration', 'Fiber', 'Sheaf', 'Groupoid', 'Category', 'Functor', 'Morphism', 'Automorphism',
      'Endomorphism', 'Kernel', 'Image',
    ],
  },
  {
    id: 'linguistics-language',
    label: 'Linguistics & Language',
    words: [
      'Language', 'Grammar', 'Syntax', 'Semantics', 'Phonetics', 'Phonology', 'Morphology', 'Pragmatics',
      'Lexicon', 'Vocabulary', 'Phrase', 'Clause', 'Sentence', 'Paragraph', 'Discourse', 'Text',
      'Context', 'Meaning', 'Reference', 'Denotation', 'Connotation', 'Ambiguity', 'Polysemy', 'Homonym',
      'Synonym', 'Antonym', 'Metaphor', 'Metonymy', 'Idiom', 'Expression', 'Utterance', 'Speech',
      'Dialect', 'Accent', 'Register', 'Style', 'Tone', 'Diction', 'Rhetoric', 'Persuasion',
      'Argumentation', 'Narrative', 'Genre', 'Structure', 'Cohesion', 'Coherence', 'Anaphora', 'Cataphora',
      'Deixis', 'Pronoun', 'Noun', 'Verb', 'Adjective', 'Adverb', 'Preposition', 'Conjunction',
      'Article', 'Interjection', 'Particle', 'Subject', 'Predicate', 'Object', 'Complement', 'Modifier',
      'Agreement', 'Inflection', 'Conjugation', 'Declension', 'Tense', 'Aspect', 'Mood', 'Voice',
      'Case', 'Number', 'Gender', 'Person', 'Root', 'Stem', 'Affix', 'Prefix',
      'Suffix', 'Infix', 'Derivation', 'Compounding', 'Blending', 'Clipping', 'Borrowing', 'Loanword',
      'Etymology', 'Origin', 'Evolution', 'Change', 'Shift', 'Variation', 'Diversity', 'Family',
      'Branch', 'Ancestor', 'Descendant', 'Cognate', 'Comparative', 'Reconstruction', 'Proto', 'Historical',
      'Diachronic', 'Synchronic', 'Structuralism', 'Generative', 'Transformational', 'Universal', 'Typology', 'Classification',
      'Category', 'Feature', 'Distinction', 'Contrast', 'Opposition', 'Marked', 'Unmarked', 'Phoneme',
      'Allophone', 'Morpheme', 'Allomorph', 'Syllable', 'Stress', 'Intonation', 'Pitch', 'Rhythm',
      'Prosody', 'Articulation', 'Vocal', 'Tract', 'Consonant', 'Vowel', 'Fricative', 'Plosive',
      'Nasal', 'Sibilant', 'Voiced', 'Voiceless', 'Aspiration', 'Place', 'Manner', 'Bilabial',
      'Alveolar', 'Velar', 'Glottal', 'Diphthong', 'Monophthong', 'Writing', 'System', 'Script',
      'Alphabet', 'Character', 'Symbol', 'Glyph', 'Orthography', 'Spelling', 'Transcription', 'Translation',
      'Interpretation', 'Bilingualism', 'Multilingualism', 'Acquisition', 'Learning', 'Fluency', 'Proficiency', 'Competence',
      'Performance', 'Comprehension', 'Production', 'Processing', 'Cognition', 'Psycholinguistics', 'Sociolinguistics', 'Communication',
      'Interaction', 'Exchange', 'Conversation', 'Dialogue', 'Turn', 'Taking', 'Politeness', 'Formality',
      'Informality', 'Convention', 'Norm', 'Standard', 'Vernacular', 'Colloquial', 'Formal', 'Informal',
      'Written', 'Spoken', 'Literacy', 'Illiteracy', 'Fluent', 'Native', 'Foreign', 'Second',
      'Immersion', 'Instruction', 'Pedagogy', 'Method', 'Approach', 'Technique', 'Strategy', 'Corpus',
      'Data', 'Analysis', 'Annotation', 'Tagging', 'Parsing', 'Model', 'Rule', 'Constraint',
      'Constituent', 'Hierarchy', 'Tree', 'Dependency', 'Relation', 'Head', 'Adjunct', 'Argument',
      'Thematic', 'Role', 'Agent', 'Patient', 'Theme', 'Experiencer', 'Instrument', 'Location',
      'Goal', 'Source', 'Palatal', 'Uvular', 'Pharyngeal', 'Labiodental', 'Interdental', 'Retroflex',
      'Lateral', 'Approximant', 'Trill', 'Tap', 'Flap', 'Affricate', 'Sonorant', 'Obstruent',
      'Coda', 'Diglossia', 'Codeswitching',
    ],
  },
  {
    id: 'visual-art-aesthetics',
    label: 'Visual Art & Aesthetics',
    words: [
      'Composition', 'Balance', 'Symmetry', 'Asymmetry', 'Proportion', 'Perspective', 'Depth', 'Dimension',
      'Form', 'Shape', 'Line', 'Contour', 'Silhouette', 'Texture', 'Pattern', 'Rhythm',
      'Movement', 'Contrast', 'Harmony', 'Unity', 'Emphasis', 'Focalpoint', 'Hierarchy', 'Scale',
      'Space', 'Negative', 'Positive', 'Foreground', 'Background', 'Middleground', 'Color', 'Hue',
      'Saturation', 'Value', 'Tone', 'Shade', 'Tint', 'Palette', 'Spectrum', 'Gradient',
      'Complementary', 'Analogous', 'Monochromatic', 'Warm', 'Cool', 'Vibrant', 'Muted', 'Pigment',
      'Medium', 'Technique', 'Brushstroke', 'Stroke', 'Gesture', 'Mark', 'Layer', 'Glaze',
      'Wash', 'Blend', 'Highlight', 'Shadow', 'Chiaroscuro', 'Illumination', 'Luminosity', 'Reflection',
      'Refraction', 'Rendering', 'Realism', 'Abstraction', 'Representation', 'Figuration', 'Nonobjective', 'Impressionism',
      'Expressionism', 'Surrealism', 'Cubism', 'Minimalism', 'Conceptualism', 'Symbolism', 'Romanticism', 'Modernism',
      'Postmodernism', 'Contemporary', 'Traditional', 'Classical', 'Style', 'Genre', 'Period', 'Era',
      'Influence', 'Inspiration', 'Vision', 'Concept', 'Idea', 'Meaning', 'Interpretation', 'Narrative',
      'Metaphor', 'Allegory', 'Motif', 'Theme', 'Subject', 'Content', 'Context', 'Intention',
      'Expression', 'Emotion', 'Mood', 'Atmosphere', 'Aesthetic', 'Beauty', 'Sublime', 'Taste',
      'Judgment', 'Criticism', 'Analysis', 'Appreciation', 'Perception', 'Experience', 'Viewer', 'Audience',
      'Spectator', 'Observer', 'Engagement', 'Reception', 'Response', 'Reaction', 'Impact', 'Effect',
      'Craft', 'Skill', 'Process', 'Method', 'Practice', 'Discipline', 'Mastery', 'Expertise',
      'Innovation', 'Experimentation', 'Exploration', 'Discovery', 'Creativity', 'Imagination', 'Originality', 'Authenticity',
      'Individuality', 'Identity', 'Voice', 'Signature', 'Approach', 'Viewpoint', 'Angle', 'Framing',
      'Arrangement', 'Placement', 'Positioning', 'Alignment', 'Grid', 'Structure', 'Format', 'Orientation',
      'Ratio', 'Golden', 'Canvas', 'Surface', 'Ground', 'Support', 'Frame', 'Border',
      'Edge', 'Margin', 'Material', 'Substrate', 'Paper', 'Fabric', 'Wood', 'Metal',
      'Stone', 'Clay', 'Ceramic', 'Sculpture', 'Relief', 'Installation', 'Assemblage', 'Collage',
      'Montage', 'Print', 'Etching', 'Engraving', 'Lithography', 'Woodcut', 'Photography', 'Exposure',
      'Aperture', 'Focus', 'Lighting', 'Digital', 'Analog', 'Development', 'Editing', 'Curation',
      'Exhibition', 'Gallery', 'Museum', 'Collection', 'Archive', 'Provenance', 'Restoration', 'Conservation',
      'Preservation', 'Display', 'Presentation', 'Setting', 'Design', 'Layout', 'Typography', 'Illustration',
      'Graphic', 'Visual', 'Communication', 'Branding', 'Vanishingpoint', 'Horizonline', 'Foreshortening', 'Modeling',
      'Sfumato', 'Tenebrism', 'Impasto', 'Underpainting', 'Pentimento', 'Varnish', 'Fresco', 'Tempera',
      'Gouache', 'Encaustic', 'Mosaic', 'Stencil', 'Screenprint', 'Monotype', 'Intaglio', 'Aquatint',
      'Drypoint', 'Mezzotint', 'Linocut', 'Watercolor', 'Grisaille', 'Trompeloeil', 'Vignette', 'Cartouche',
      'Frieze', 'Pointillism', 'Divisionism', 'Fauvism', 'Vorticism',
    ],
  },
  {
    id: 'meditation-mindfulness',
    label: 'Meditation & Mindfulness',
    words: [
      'Meditation', 'Mindfulness', 'Awareness', 'Presence', 'Attention', 'Focus', 'Concentration', 'Breath',
      'Breathing', 'Inhale', 'Exhale', 'Stillness', 'Silence', 'Quiet', 'Calm', 'Peace',
      'Serenity', 'Tranquility', 'Equanimity', 'Balance', 'Centering', 'Grounding', 'Rootedness', 'Stability',
      'Steadiness', 'Nowness', 'Immediacy', 'Moment', 'Instant', 'Observation', 'Witnessing', 'Noticing',
      'Perceiving', 'Sensing', 'Feeling', 'Body', 'Sensation', 'Physicality', 'Embodiment', 'Posture',
      'Alignment', 'Relaxation', 'Release', 'Letting', 'Surrender', 'Acceptance', 'Nonjudgment', 'Nonattachment',
      'Detachment', 'Nonresistance', 'Allowing', 'Openness', 'Receptivity', 'Spaciousness', 'Expansiveness', 'Emptiness',
      'Void', 'Nothingness', 'Fullness', 'Wholeness', 'Completeness', 'Unity', 'Oneness', 'Interconnection',
      'Interbeing', 'Connection', 'Belonging', 'Compassion', 'Kindness', 'Loving', 'Warmth', 'Gentleness',
      'Softness', 'Tenderness', 'Care', 'Nurturing', 'Healing', 'Wellbeing', 'Integration', 'Harmony',
      'Coherence', 'Equilibrium', 'Homeostasis', 'Regulation', 'Selfregulation', 'Discipline', 'Practice', 'Ritual',
      'Routine', 'Habit', 'Cultivation', 'Development', 'Growth', 'Evolution', 'Transformation', 'Awakening',
      'Enlightenment', 'Realization', 'Insight', 'Clarity', 'Understanding', 'Wisdom', 'Knowing', 'Recognition',
      'Discernment', 'Discrimination', 'Onepointedness', 'Singlepointed', 'Absorption', 'Immersion', 'Flow', 'Effortlessness',
      'Ease', 'Naturalness', 'Simplicity', 'Purity', 'Transparency', 'Lucidity', 'Vividness', 'Aliveness',
      'Vitality', 'Consciousness', 'Perception', 'Cognition', 'Mind', 'Thought', 'Thinking', 'Mentation',
      'Ideation', 'Concept', 'Belief', 'Assumption', 'Judgment', 'Evaluation', 'Reactivity', 'Response',
      'Reflex', 'Impulse', 'Urge', 'Craving', 'Attachment', 'Aversion', 'Desire', 'Wanting',
      'Grasping', 'Clinging', 'Fixation', 'Rumination', 'Distraction', 'Wandering', 'Restlessness', 'Agitation',
      'Turbulence', 'Chaos', 'Disorder', 'Confusion', 'Clouding', 'Obscuration', 'Veil', 'Illusion',
      'Delusion', 'Ignorance', 'Unconsciousness', 'Automaticity', 'Habituation', 'Conditioning', 'Pattern', 'Tendency',
      'Disposition', 'Temperament', 'Character', 'Nature', 'Essence', 'Being', 'Existence', 'Selfhood',
      'Identity', 'Ego', 'Selflessness', 'Egolessness', 'Transcendence', 'Immanence', 'Sacredness', 'Reverence',
      'Devotion', 'Faith', 'Trust', 'Confidence', 'Courage', 'Vulnerability', 'Authenticity', 'Honesty',
      'Sincerity', 'Integrity', 'Congruence', 'Purpose', 'Meaning', 'Intention', 'Aspiration', 'Vow',
      'Commitment', 'Dedication', 'Effort', 'Diligence', 'Perseverance', 'Patience', 'Endurance', 'Resilience',
      'Fortitude', 'Strength', 'Power', 'Energy', 'Lifeforce', 'Prana', 'Chi', 'Qi',
      'Vibration', 'Frequency', 'Resonance', 'Attunement', 'Sangha', 'Dharma', 'Karma', 'Samsara',
      'Nirvana', 'Satori', 'Kensho', 'Zazen', 'Vipassana', 'Samatha', 'Metta', 'Mudra',
      'Mantra', 'Yantra', 'Chakra', 'Kundalini', 'Bandha', 'Asana', 'Pranayama', 'Satsang',
      'Ashram', 'Guru', 'Disciple', 'Retreat', 'Contemplation', 'Solitude', 'Renunciation', 'Austerity',
      'Humility', 'Equanimous', 'Beginnersmind',
    ],
  },
  {
    id: 'leadership-strategy',
    label: 'Leadership & Strategy',
    words: [
      'Leadership', 'Vision', 'Mission', 'Purpose', 'Strategy', 'Tactic', 'Execution', 'Implementation',
      'Planning', 'Direction', 'Guidance', 'Influence', 'Inspiration', 'Motivation', 'Empowerment', 'Delegation',
      'Accountability', 'Responsibility', 'Ownership', 'Initiative', 'Decisiveness', 'Judgment', 'Discernment', 'Wisdom',
      'Insight', 'Perspective', 'Foresight', 'Anticipation', 'Adaptability', 'Agility', 'Flexibility', 'Resilience',
      'Perseverance', 'Determination', 'Commitment', 'Dedication', 'Focus', 'Priority', 'Alignment', 'Coordination',
      'Collaboration', 'Cooperation', 'Teamwork', 'Synergy', 'Partnership', 'Alliance', 'Coalition', 'Network',
      'Relationship', 'Trust', 'Credibility', 'Integrity', 'Authenticity', 'Transparency', 'Honesty', 'Fairness',
      'Respect', 'Empathy', 'Compassion', 'Humility', 'Confidence', 'Courage', 'Boldness', 'Risk',
      'Innovation', 'Creativity', 'Disruption', 'Transformation', 'Change', 'Growth', 'Development', 'Improvement',
      'Excellence', 'Quality', 'Performance', 'Achievement', 'Success', 'Impact', 'Outcome', 'Result',
      'Objective', 'Goal', 'Target', 'Milestone', 'Benchmark', 'Metric', 'Measurement', 'Evaluation',
      'Assessment', 'Feedback', 'Iteration', 'Refinement', 'Optimization', 'Efficiency', 'Effectiveness', 'Productivity',
      'Value', 'Contribution', 'Culture', 'Environment', 'Climate', 'Atmosphere', 'Morale', 'Engagement',
      'Satisfaction', 'Fulfillment', 'Wellbeing', 'Communication', 'Clarity', 'Articulation', 'Messaging', 'Narrative',
      'Storytelling', 'Persuasion', 'Negotiation', 'Diplomacy', 'Mediation', 'Conflict', 'Resolution', 'Management',
      'Problemsolving', 'Decisionmaking', 'Analysis', 'Diagnosis', 'Solution', 'Ideation', 'Brainstorming', 'Experimentation',
      'Prototyping', 'Testing', 'Validation', 'Learning', 'Adaptation', 'Positioning', 'Differentiation', 'Advantage',
      'Competitive', 'Market', 'Opportunity', 'Threat', 'Strength', 'Weakness', 'Roadmap', 'Framework',
      'Model', 'Approach', 'Methodology', 'Process', 'System', 'Structure', 'Organization', 'Hierarchy',
      'Governance', 'Oversight', 'Supervision', 'Administration', 'Operations', 'Deployment', 'Rollout', 'Launch',
      'Scaling', 'Expansion', 'Progress', 'Advancement', 'Succession', 'Continuity', 'Sustainability', 'Legacy',
      'Reputation', 'Brand', 'Identity', 'Values', 'Principles', 'Ethics', 'Standards', 'Norms',
      'Expectations', 'Compliance', 'Mitigation', 'Contingency', 'Preparedness', 'Crisis', 'Response', 'Recovery',
      'Transition', 'Evolution', 'Reinvention', 'Renewal', 'Mentorship', 'Coaching', 'Training', 'Education',
      'Capability', 'Competency', 'Skill', 'Expertise', 'Mastery', 'Standard', 'Bestpractice', 'Continuous',
      'Stewardship', 'Custodianship', 'Trusteeship', 'Sponsorship', 'Championing', 'Advocacy', 'Endorsement', 'Buyin',
      'Consensus', 'Cascading', 'Onboarding', 'Ramping', 'Institutionalizing', 'Formalizing', 'Codifying', 'Documenting',
      'Standardizing', 'Streamlining', 'Simplifying', 'Consolidating', 'Rationalizing', 'Prioritizing', 'Sequencing', 'Phasing',
      'Staging', 'Pacing', 'Timing', 'Cadence', 'Momentum', 'Traction', 'Leverage', 'Multiplier',
      'Amplification', 'Compounding', 'Snowballing', 'Escalating', 'Deescalating', 'Calibrating', 'Finetuning', 'Adjusting',
      'Recalibrating', 'Pivoting', 'Repositioning', 'Reorienting', 'Realigning', 'Restructuring', 'Reorganizing', 'Redesigning',
      'Bellwether', 'Groundswell', 'Flywheel',
    ],
  },
  {
    id: 'nutrition-wellness',
    label: 'Nutrition & Wellness',
    words: [
      'Nutrition', 'Nutrient', 'Vitamin', 'Mineral', 'Protein', 'Carbohydrate', 'Fat', 'Fiber',
      'Calorie', 'Energy', 'Metabolism', 'Digestion', 'Absorption', 'Assimilation', 'Enzyme', 'Hormone',
      'Balance', 'Homeostasis', 'Regulation', 'Wellness', 'Health', 'Vitality', 'Strength', 'Endurance',
      'Stamina', 'Fitness', 'Exercise', 'Movement', 'Activity', 'Physical', 'Cardiovascular', 'Respiratory',
      'Muscular', 'Skeletal', 'Immune', 'System', 'Function', 'Resilience', 'Recovery', 'Repair',
      'Regeneration', 'Renewal', 'Healing', 'Restoration', 'Rehabilitation', 'Prevention', 'Protection', 'Defense',
      'Immunity', 'Resistance', 'Inflammation', 'Antioxidant', 'Freeradical', 'Oxidation', 'Stress', 'Cortisol',
      'Adrenaline', 'Sleep', 'Rest', 'Relaxation', 'Circadian', 'Rhythm', 'Cycle', 'Pattern',
      'Routine', 'Habit', 'Hydration', 'Water', 'Electrolyte', 'Fluid', 'Circulation', 'Blood',
      'Flow', 'Pressure', 'Heart', 'Rate', 'Pulse', 'Breathing', 'Respiration', 'Oxygen',
      'Capacity', 'Lung', 'Digestive', 'Gut', 'Microbiome', 'Bacteria', 'Flora', 'Fermentation',
      'Probiotic', 'Prebiotic', 'Deficiency', 'Excess', 'Toxicity', 'Moderation', 'Portion', 'Serving',
      'Intake', 'Consumption', 'Diet', 'Eating', 'Meal', 'Snack', 'Fasting', 'Feasting',
      'Restriction', 'Elimination', 'Supplementation', 'Wholefood', 'Processed', 'Refined', 'Natural', 'Organic',
      'Synthetic', 'Additive', 'Preservative', 'Ingredient', 'Composition', 'Quality', 'Freshness', 'Preparation',
      'Cooking', 'Method', 'Technique', 'Preservation', 'Storage', 'Handling', 'Safety', 'Sanitation',
      'Hygiene', 'Contamination', 'Pathogen', 'Virus', 'Infection', 'Disease', 'Illness', 'Symptom',
      'Diagnosis', 'Treatment', 'Therapy', 'Medicine', 'Remedy', 'Intervention', 'Management', 'Care',
      'Support', 'Wellbeing', 'Equilibrium', 'Harmony', 'Integration', 'Wholeness', 'Aliveness', 'Radiance',
      'Glow', 'Complexion', 'Skin', 'Appearance', 'Vigor', 'Robustness', 'Adaptability', 'Flexibility',
      'Mobility', 'Agility', 'Coordination', 'Stability', 'Posture', 'Alignment', 'Structure', 'Mechanics',
      'Biomechanics', 'Physiology', 'Anatomy', 'Organ', 'Tissue', 'Cell', 'Growth', 'Development',
      'Maturation', 'Aging', 'Longevity', 'Lifespan', 'Healthspan', 'Life', 'Fulfillment', 'Satisfaction',
      'Contentment', 'Happiness', 'Purpose', 'Meaning', 'Micronutrient', 'Macronutrient', 'Phytonutrient', 'Bioavailability',
      'Metabolite', 'Catabolism', 'Anabolism', 'Glycolysis', 'Gluconeogenesis', 'Lipolysis', 'Lipogenesis', 'Ketosis',
      'Thermogenesis', 'Satiety', 'Appetite', 'Craving', 'Palatability', 'Mastication', 'Peristalsis', 'Secretion',
      'Excretion', 'Detoxification', 'Cleansing', 'Purification', 'Hardiness', 'Suppleness', 'Elasticity', 'Rejuvenation',
      'Revitalization', 'Temperance', 'Discipline', 'Consistency', 'Ritual', 'Selfcare', 'Nurture', 'Nourish',
      'Sustain', 'Fortify', 'Strengthen', 'Cultivate', 'Foster', 'Enhance', 'Optimize', 'Maximize',
      'Improve', 'Elevate', 'Uplift', 'Empower', 'Energize', 'Invigorate', 'Refresh', 'Renew',
      'Replenish', 'Restore', 'Osmolarity', 'Turgor', 'Enervation', 'Invigoration', 'Wholesomeness', 'Vim',
      'Zest', 'Hardihood', 'Sprightliness',
    ],
  },
  {
    id: 'technology-innovation',
    label: 'Technology & Innovation',
    words: [
      'Technology', 'Innovation', 'Invention', 'Discovery', 'Development', 'Engineering', 'Design', 'Prototype',
      'Iteration', 'Testing', 'Algorithm', 'Software', 'Hardware', 'System', 'Network', 'Infrastructure',
      'Platform', 'Architecture', 'Framework', 'Protocol', 'Interface', 'Integration', 'Automation', 'Robotics',
      'Artificial', 'Intelligence', 'Machine', 'Learning', 'Neural', 'Data', 'Analytics', 'Processing',
      'Computation', 'Storage', 'Memory', 'Bandwidth', 'Latency', 'Throughput', 'Performance', 'Efficiency',
      'Optimization', 'Scalability', 'Reliability', 'Security', 'Privacy', 'Encryption', 'Authentication', 'Verification',
      'Validation', 'Cloud', 'Computing', 'Server', 'Database', 'Application', 'Program', 'Code',
      'Programming', 'Deployment', 'Cybersecurity', 'Firewall', 'Vulnerability', 'Threat', 'Attack', 'Defense',
      'Protection', 'Resilience', 'Recovery', 'Backup', 'Internet', 'Connectivity', 'Wireless', 'Broadband',
      'Signal', 'Frequency', 'Transmission', 'Reception', 'Communication', 'Digital', 'Analog', 'Binary',
      'Bit', 'Byte', 'Pixel', 'Resolution', 'Display', 'Screen', 'Interaction', 'Usability',
      'Experience', 'Accessibility', 'Ergonomics', 'Functionality', 'Feature', 'Capability', 'Function', 'Sensor',
      'Actuator', 'Circuit', 'Chip', 'Processor', 'Microcontroller', 'Semiconductor', 'Transistor', 'Component',
      'Module', 'Assembly', 'Manufacturing', 'Production', 'Fabrication', 'Prototyping', 'Disruption', 'Transformation',
      'Evolution', 'Advancement', 'Progress', 'Breakthrough', 'Milestone', 'Achievement', 'Research', 'Experimentation',
      'Exploration', 'Startup', 'Entrepreneur', 'Venture', 'Investment', 'Funding', 'Growth', 'Scaling',
      'Expansion', 'Market', 'Adoption', 'Digitalization', 'Productivity', 'Streamlining', 'Simplification', 'Ecosystem',
      'Marketplace', 'Interoperability', 'Compatibility', 'Standard', 'Specification', 'Blockchain', 'Cryptocurrency', 'Ledger',
      'Distributed', 'Decentralized', 'Consensus', 'Transaction', 'Contract', 'Smart', 'Virtual', 'Augmented',
      'Reality', 'Simulation', 'Immersion', 'Interactive', 'Environment', 'Rendering', 'Quantum', 'Superposition',
      'Entanglement', 'Qubit', 'Cryptography', 'Biotechnology', 'Genomics', 'Synthesis', 'Modification', 'Editing',
      'Sequencing', 'Analysis', 'Nanotechnology', 'Material', 'Science', 'Middleware', 'Firmware', 'Kernel',
      'Runtime', 'Compiler', 'Interpreter', 'Debugger', 'Repository', 'Versioning', 'Branching', 'Merging',
      'Refactoring', 'Modularity', 'Abstraction', 'Encapsulation', 'Inheritance', 'Polymorphism', 'Instantiation', 'Serialization',
      'Deserialization', 'Marshaling', 'Parsing', 'Tokenizing', 'Compiling', 'Linking', 'Loading', 'Execution',
      'Threading', 'Concurrency', 'Parallelism', 'Synchronization', 'Deadlock', 'Racecondition', 'Bottleneck', 'Throttling',
      'Caching', 'Indexing', 'Querying', 'Aggregating', 'Filtering', 'Sorting', 'Partitioning', 'Sharding',
      'Replication', 'Clustering', 'Loadbalancing', 'Failover', 'Redundancy', 'Faulttolerance', 'Observability', 'Monitoring',
      'Logging', 'Alerting', 'Provisioning', 'Orchestration', 'Containerization', 'Virtualization', 'Emulation', 'Instrumentation',
      'Telemetry', 'Pipeline', 'Continuous Integration', 'Delivery', 'Rollback', 'Portability', 'Extensibility', 'Maintainability',
      'Testability', 'Availability', 'Multithreading', 'Multiprocessing', 'Heuristics', 'Backpropagation', 'Gradientdescent', 'Overfitting',
      'Regularization', 'Hyperparameter',
    ],
  },
  {
    id: 'law-justice',
    label: 'Law & Justice',
    words: [
      'Law', 'Justice', 'Legal', 'Legislation', 'Statute', 'Regulation', 'Code', 'Constitution',
      'Amendment', 'Provision', 'Clause', 'Article', 'Section', 'Precedent', 'Jurisprudence', 'Doctrine',
      'Principle', 'Rule', 'Standard', 'Test', 'Court', 'Tribunal', 'Judge', 'Magistrate',
      'Jury', 'Verdict', 'Judgment', 'Ruling', 'Decision', 'Opinion', 'Dissent', 'Concurrence',
      'Appeal', 'Appellate', 'Jurisdiction', 'Venue', 'Standing', 'Litigation', 'Lawsuit', 'Plaintiff',
      'Defendant', 'Prosecution', 'Defense', 'Counsel', 'Attorney', 'Lawyer', 'Advocate', 'Representation',
      'Testimony', 'Evidence', 'Exhibit', 'Witness', 'Deposition', 'Discovery', 'Subpoena', 'Summons',
      'Complaint', 'Motion', 'Petition', 'Brief', 'Argument', 'Hearing', 'Trial', 'Proceeding',
      'Procedure', 'Process', 'Due', 'Rights', 'Liberty', 'Freedom', 'Equality', 'Fairness',
      'Impartiality', 'Neutrality', 'Objectivity', 'Integrity', 'Accountability', 'Transparency', 'Legitimacy', 'Authority',
      'Power', 'Sovereignty', 'Governance', 'Compliance', 'Enforcement', 'Violation', 'Infraction', 'Offense',
      'Crime', 'Felony', 'Misdemeanor', 'Liability', 'Culpability', 'Negligence', 'Intent', 'Malice',
      'Fraud', 'Misconduct', 'Breach', 'Contract', 'Agreement', 'Obligation', 'Duty', 'Responsibility',
      'Consent', 'Capacity', 'Competence', 'Guardianship', 'Custody', 'Property', 'Ownership', 'Title',
      'Deed', 'Estate', 'Inheritance', 'Trust', 'Bequest', 'Testament', 'Covenant', 'Warranty',
      'Indemnity', 'Damages', 'Remedy', 'Compensation', 'Restitution', 'Redress', 'Injunction', 'Order',
      'Decree', 'Mandate', 'Sanction', 'Penalty', 'Fine', 'Punishment', 'Sentence', 'Incarceration',
      'Probation', 'Parole', 'Rehabilitation', 'Reform', 'Deterrence', 'Retribution', 'Restoration', 'Mediation',
      'Arbitration', 'Negotiation', 'Settlement', 'Resolution', 'Reconciliation', 'Compromise', 'Treaty', 'Convention',
      'Pact', 'Accord', 'Alliance', 'International', 'Domestic', 'Federal', 'State', 'Municipal',
      'Civil', 'Criminal', 'Administrative', 'Constitutional', 'Statutory', 'Common', 'Custom', 'Tradition',
      'Stare', 'Decisis', 'Interpretation', 'Construction', 'Analysis', 'Reasoning', 'Logic', 'Rhetoric',
      'Persuasion', 'Advocacy', 'Guidance', 'Advice', 'Consultation', 'Ethics', 'Morality', 'Value',
      'Norm', 'Habeas Corpus', 'Mens Rea', 'Actus Reus', 'Prima Facie', 'Amicus Curiae', 'Certiorari', 'Mandamus',
      'Estoppel', 'Latches', 'Waiver', 'Ratification', 'Recusal', 'Impeachment', 'Indictment', 'Arraignment',
      'Plea Bargain', 'Acquittal', 'Conviction', 'Sentencing', 'Guideline', 'Aggravating', 'Mitigating', 'Circumstance',
      'Culpable', 'Exculpatory', 'Inculpatory', 'Admissible', 'Inadmissible', 'Hearsay', 'Privilege', 'Confidentiality',
      'Disclosure', 'Interrogatory', 'Affidavit', 'Notarization', 'Certification', 'Attestation', 'Validation', 'Codification',
      'Repeal', 'Abrogation', 'Supersession', 'Preemption', 'Devolution', 'Delegation', 'Subsidiarity', 'Proportionality',
      'Reasonableness', 'Rationality', 'Arbitrariness', 'Capriciousness', 'Deference', 'Scrutiny', 'Review', 'Oversight',
      'Locus Standi', 'Res Judicata', 'Voir Dire', 'Amicus Brief', 'Bench Trial', 'Statute Of Limitations', 'Burden Of Proof', 'Chain Of Custody',
      'Precedent Setting', 'Judicial Restraint', 'Judicial Activism', 'Injunctive Relief', 'Punitive Damages',
    ],
  },
  {
    id: 'anthropology-culture',
    label: 'Anthropology & Culture',
    words: [
      'Culture', 'Society', 'Civilization', 'Community', 'Tradition', 'Custom', 'Ritual', 'Ceremony',
      'Practice', 'Belief', 'Value', 'Norm', 'Convention', 'Behavior', 'Interaction', 'Relationship',
      'Kinship', 'Family', 'Clan', 'Tribe', 'Ethnicity', 'Identity', 'Heritage', 'Ancestry',
      'Lineage', 'Descent', 'Generation', 'Elder', 'Youth', 'Rite', 'Passage', 'Initiation',
      'Marriage', 'Birth', 'Death', 'Mourning', 'Celebration', 'Festival', 'Feast', 'Gathering',
      'Language', 'Communication', 'Symbol', 'Meaning', 'Interpretation', 'Narrative', 'Myth', 'Legend',
      'Folklore', 'Oral', 'Storytelling', 'Wisdom', 'Knowledge', 'Transmission', 'Learning', 'Socialization',
      'Enculturation', 'Adaptation', 'Assimilation', 'Integration', 'Diversity', 'Pluralism', 'Multiculturalism', 'Ethnocentrism',
      'Relativism', 'Universalism', 'Particularism', 'Globalization', 'Localization', 'Migration', 'Diaspora', 'Displacement',
      'Settlement', 'Colonization', 'Indigenous', 'Native', 'Aboriginal', 'Autochthonous', 'Foreign', 'Immigrant',
      'Refugee', 'Nomad', 'Sedentary', 'Agrarian', 'Pastoral', 'Hunter', 'Gatherer', 'Subsistence',
      'Economy', 'Trade', 'Exchange', 'Reciprocity', 'Gift', 'Barter', 'Commerce', 'Market',
      'Production', 'Labor', 'Division', 'Hierarchy', 'Stratification', 'Class', 'Caste', 'Status',
      'Rank', 'Prestige', 'Power', 'Authority', 'Leadership', 'Governance', 'Politics', 'Institution',
      'Organization', 'Structure', 'System', 'Order', 'Chaos', 'Conflict', 'Cooperation', 'Alliance',
      'Rivalry', 'Competition', 'Solidarity', 'Cohesion', 'Fragmentation', 'Unity', 'Acculturation', 'Syncretism',
      'Hybridity', 'Fusion', 'Blending', 'Innovation', 'Invention', 'Diffusion', 'Artifact', 'Material',
      'Technology', 'Tool', 'Craft', 'Art', 'Aesthetic', 'Expression', 'Creativity', 'Religion',
      'Spirituality', 'Sacred', 'Profane', 'Worship', 'Deity', 'Ancestor', 'Spirit', 'Shaman',
      'Priest', 'Sacrifice', 'Offering', 'Prayer', 'Meditation', 'Cosmology', 'Worldview', 'Philosophy',
      'Ethics', 'Morality', 'Taboo', 'Prohibition', 'Sanction', 'Deviance', 'Conformity', 'Rebellion',
      'Resistance', 'Revolution', 'Change', 'Continuity', 'Persistence', 'Resilience', 'Evolution', 'Development',
      'Modernization', 'Preservation', 'Revitalization', 'Documentation', 'Ethnography', 'Fieldwork', 'Observation', 'Participant',
      'Interview', 'Analysis', 'Autoethnography', 'Informant', 'Interlocutor', 'Gatekeeper', 'Rapport', 'Reflexivity',
      'Positionality', 'Emic', 'Etic', 'Insider', 'Outsider', 'Fieldnote', 'Thickdescription', 'Interpretivism',
      'Functionalism', 'Structuralfunctionalism', 'Poststructuralism', 'Postcolonialism', 'Subaltern', 'Hegemony', 'Habitus', 'Capital',
      'Symbolic', 'Cultural', 'Social', 'Economic', 'Field', 'Doxa', 'Praxis', 'Agency',
      'Determinism', 'Voluntarism', 'Redistribution', 'Potlatch', 'Bigman', 'Chiefdom', 'Statelessness', 'Egalitarianism',
      'Ranking', 'Complexity', 'Sedentism', 'Nomadism', 'Transhumance', 'Pastoralism', 'Horticulture', 'Foraging',
      'Domestication', 'Sedentarization', 'Urbanization', 'Westernization', 'Indigeneity', 'Sovereignty', 'Selfgovernance', 'Autonomy',
      'Recognition', 'Repatriation', 'Restitution', 'Decolonization', 'Consanguinity', 'Affinity', 'Matrilineal', 'Patrilineal',
      'Endogamy', 'Exogamy', 'Totemism',
    ],
  },
  {
    id: 'human-psychology',
    label: 'Human Psychology',
    words: [
      'Psychology', 'Behavior', 'Cognition', 'Perception', 'Sensation', 'Attention', 'Memory', 'Learning',
      'Motivation', 'Emotion', 'Personality', 'Temperament', 'Character', 'Identity', 'Selfconcept', 'Selfesteem',
      'Confidence', 'Consciousness', 'Awareness', 'Unconscious', 'Subconscious', 'Instinct', 'Drive', 'Need',
      'Desire', 'Impulse', 'Reflex', 'Habit', 'Pattern', 'Tendency', 'Disposition', 'Trait',
      'Attitude', 'Belief', 'Value', 'Interpretation', 'Judgment', 'Bias', 'Heuristic', 'Reasoning',
      'Logic', 'Intuition', 'Insight', 'Understanding', 'Comprehension', 'Intelligence', 'Processing', 'Development',
      'Growth', 'Maturation', 'Stage', 'Milestone', 'Attachment', 'Bonding', 'Relationship', 'Interaction',
      'Communication', 'Empathy', 'Compassion', 'Sympathy', 'Altruism', 'Cooperation', 'Competition', 'Conflict',
      'Aggression', 'Hostility', 'Anxiety', 'Fear', 'Stress', 'Coping', 'Resilience', 'Adaptation',
      'Adjustment', 'Regulation', 'Control', 'Discipline', 'Willpower', 'Selfcontrol', 'Impulsivity', 'Restraint',
      'Inhibition', 'Suppression', 'Repression', 'Defense', 'Mechanism', 'Denial', 'Projection', 'Displacement',
      'Rationalization', 'Sublimation', 'Regression', 'Transference', 'Countertransference', 'Therapy', 'Treatment', 'Intervention',
      'Counseling', 'Diagnosis', 'Disorder', 'Syndrome', 'Symptom', 'Condition', 'Assessment', 'Evaluation',
      'Testing', 'Measurement', 'Scale', 'Instrument', 'Questionnaire', 'Survey', 'Interview', 'Observation',
      'Experiment', 'Study', 'Research', 'Hypothesis', 'Theory', 'Model', 'Framework', 'Paradigm',
      'Approach', 'Perspective', 'School', 'Behaviorism', 'Cognitivism', 'Humanism', 'Psychoanalysis', 'Gestalt',
      'Constructivism', 'Cognitive', 'Social', 'Emotional', 'Moral', 'Ethical', 'Decisionmaking', 'Problemsolving',
      'Creativity', 'Imagination', 'Fantasy', 'Dream', 'Sleep', 'Altered', 'State', 'Arousal',
      'Stimulation', 'Illusion', 'Hallucination', 'Distortion', 'Reality', 'Selfawareness', 'Introspection', 'Reflection',
      'Metacognition', 'Mindfulness', 'Presence', 'Focus', 'Concentration', 'Vigilance', 'Alertness', 'Goal',
      'Aspiration', 'Ambition', 'Achievement', 'Success', 'Failure', 'Frustration', 'Satisfaction', 'Fulfillment',
      'Happiness', 'Wellbeing', 'Flourishing', 'Hardiness', 'Grit', 'Perseverance', 'Determination', 'Selfefficacy',
      'Agency', 'Autonomy', 'Independence', 'Dependence', 'Interdependence', 'Separation', 'Individuation', 'Rumination',
      'Perseveration', 'Fixation', 'Preoccupation', 'Ambivalence', 'Dissonance', 'Congruence', 'Incongruence', 'Assimilation',
      'Accommodation', 'Equilibration', 'Scaffolding', 'Internalization', 'Externalization', 'Introjection', 'Identification', 'Detachment',
      'Enmeshment', 'Boundary', 'Differentiation', 'Fusion', 'Triangulation', 'Codependence', 'Reciprocity', 'Mutuality',
      'Vulnerability', 'Buoyancy', 'Optimism', 'Pessimism', 'Fatalism', 'Determinism', 'Freewill', 'Efficacy',
      'Mastery', 'Competence', 'Relatedness', 'Belonging', 'Acceptance', 'Validation', 'Recognition', 'Affirmation',
      'Reinforcement', 'Punishment', 'Extinction', 'Generalization', 'Discrimination', 'Conditioning', 'Association', 'Habituation',
      'Sensitization', 'Priming', 'Framing', 'Anchoring', 'Alexithymia', 'Interoceptive', 'Proprioceptive', 'Neuroticism',
      'Extraversion', 'Agreeableness', 'Conscientiousness', 'Openness', 'Selfmonitoring', 'Impressionmanagement', 'Reactance', 'Cognitivedissonance',
      'Overjustification', 'Attributionerror',
    ],
  },
  {
    id: 'chemistry-matter',
    label: 'Chemistry & Matter',
    words: [
      'Element', 'Atom', 'Molecule', 'Compound', 'Mixture', 'Solution', 'Solvent', 'Solute',
      'Concentration', 'Dilution', 'Reaction', 'Catalyst', 'Enzyme', 'Substrate', 'Product', 'Reactant',
      'Equilibrium', 'Kinetics', 'Rate', 'Mechanism', 'Bond', 'Covalent', 'Ionic', 'Metallic',
      'Hydrogen', 'Polar', 'Nonpolar', 'Electronegativity', 'Valence', 'Electron', 'Proton', 'Neutron',
      'Nucleus', 'Isotope', 'Ion', 'Cation', 'Anion', 'Charge', 'Orbital', 'Shell',
      'Periodic', 'Table', 'Group', 'Period', 'Metal', 'Nonmetal', 'Metalloid', 'Alkali',
      'Halogen', 'Noble', 'Gas', 'Liquid', 'Solid', 'Plasma', 'Phase', 'Transition',
      'Melting', 'Boiling', 'Freezing', 'Condensation', 'Sublimation', 'Deposition', 'Vaporization', 'Evaporation',
      'Diffusion', 'Osmosis', 'Density', 'Viscosity', 'Solubility', 'Polarity', 'Acid', 'Base',
      'Ph', 'Neutralization', 'Buffer', 'Titration', 'Indicator', 'Oxidation', 'Reduction', 'Redox',
      'Electrolysis', 'Electrode', 'Anode', 'Cathode', 'Battery', 'Cell', 'Voltage', 'Current',
      'Conductivity', 'Resistance', 'Precipitate', 'Sediment', 'Filtration', 'Distillation', 'Chromatography', 'Separation',
      'Purification', 'Synthesis', 'Decomposition', 'Combustion', 'Corrosion', 'Rust', 'Polymer', 'Monomer',
      'Polymerization', 'Plastic', 'Resin', 'Fiber', 'Composite', 'Organic', 'Inorganic', 'Carbon',
      'Hydrocarbon', 'Alkane', 'Alkene', 'Alkyne', 'Aromatic', 'Functional', 'Alcohol', 'Aldehyde',
      'Ketone', 'Ester', 'Ether', 'Amine', 'Amide', 'Carboxylic', 'Protein', 'Amino',
      'Peptide', 'Catalysis', 'Metabolism', 'Biochemistry', 'Biosynthesis', 'Nucleic', 'Dna', 'Rna',
      'Gene', 'Chromosome', 'Genome', 'Mutation', 'Replication', 'Transcription', 'Translation', 'Expression',
      'Regulation', 'Thermodynamics', 'Enthalpy', 'Entropy', 'Freeenergy', 'Spontaneity', 'Reversibility', 'Irreversibility',
      'Heat', 'Temperature', 'Pressure', 'Volume', 'Gaslaw', 'Ideal', 'Real', 'Behavior',
      'State', 'Function', 'System', 'Surroundings', 'Isolated', 'Closed', 'Open', 'Boundary',
      'Process', 'Cycle', 'Efficiency', 'Work', 'Energy', 'Conservation', 'Transformation', 'Transfer',
      'Radiation', 'Conduction', 'Convection', 'Insulation', 'Conductor', 'Semiconductor', 'Superconductor', 'Material',
      'Property', 'Structure', 'Crystal', 'Lattice', 'Amorphous', 'Alloy', 'Ceramic', 'Metallurgy',
      'Allotrope', 'Isomer', 'Stereoisomer', 'Enantiomer', 'Diastereomer', 'Racemate', 'Chirality', 'Conformation',
      'Configuration', 'Substitution', 'Elimination', 'Addition', 'Rearrangement', 'Pericyclic', 'Sigmatropic', 'Electrocyclic',
      'Nucleophile', 'Electrophile', 'Leavinggroup', 'Carbocation', 'Carbanion', 'Freeradical', 'Homolysis', 'Heterolysis',
      'Titrant', 'Analyte', 'Standard', 'Calibration', 'Assay', 'Spectroscopy', 'Chromatogram', 'Massspectrometry',
      'Fragmentation', 'Ionization', 'Detector', 'Column', 'Elution', 'Retention', 'Resolution', 'Purity',
      'Yield', 'Selectivity', 'Stoichiometry', 'Molarity', 'Molality', 'Normality', 'Saturation', 'Supersaturation',
      'Nucleation', 'Crystallization', 'Recrystallization', 'Extraction', 'Partitioning', 'Emulsion', 'Suspension', 'Colloid',
      'Aerosol', 'Foam', 'Gel', 'Sol',
    ],
  },
  {
    id: 'world-history',
    label: 'World History',
    words: [
      'Civilization', 'Empire', 'Kingdom', 'Dynasty', 'Monarchy', 'Republic', 'Democracy', 'Oligarchy',
      'Aristocracy', 'Sovereignty', 'Conquest', 'Expansion', 'Colonization', 'Independence', 'Revolution', 'Rebellion',
      'Uprising', 'Insurgency', 'Resistance', 'Liberation', 'Treaty', 'Alliance', 'War', 'Battle',
      'Campaign', 'Siege', 'Invasion', 'Occupation', 'Annexation', 'Territory', 'Border', 'Frontier',
      'Migration', 'Settlement', 'Trade', 'Route', 'Exchange', 'Commerce', 'Economy', 'Agriculture',
      'Industry', 'Technology', 'Innovation', 'Invention', 'Discovery', 'Exploration', 'Expedition', 'Navigation',
      'Voyage', 'Diplomacy', 'Negotiation', 'Statesmanship', 'Governance', 'Administration', 'Bureaucracy', 'Legislation',
      'Constitution', 'Reform', 'Movement', 'Ideology', 'Doctrine', 'Philosophy', 'Religion', 'Faith',
      'Belief', 'Institution', 'Society', 'Culture', 'Heritage', 'Tradition', 'Legacy', 'Monument',
      'Artifact', 'Ruin', 'Excavation', 'Archaeology', 'Chronicle', 'Record', 'Document', 'Manuscript',
      'Archive', 'Source', 'Evidence', 'Interpretation', 'Narrative', 'Perspective', 'Bias', 'Revision',
      'Historiography', 'Era', 'Epoch', 'Period', 'Age', 'Century', 'Millennium', 'Timeline',
      'Chronology', 'Sequence', 'Succession', 'Transition', 'Transformation', 'Continuity', 'Change', 'Progress',
      'Decline', 'Collapse', 'Fall', 'Rise', 'Golden', 'Renaissance', 'Enlightenment', 'Reformation',
      'Industrialization', 'Modernization', 'Globalization', 'Imperialism', 'Nationalism', 'Federalism', 'Autonomy', 'Selfdetermination',
      'Statehood', 'Citizenship', 'Rights', 'Freedom', 'Liberty', 'Equality', 'Justice', 'Oppression',
      'Persecution', 'Discrimination', 'Slavery', 'Emancipation', 'Abolition', 'Struggle', 'Activism', 'Advocacy',
      'Protest', 'Demonstration', 'Strike', 'Boycott', 'Petition', 'Cause', 'Leader', 'Ruler',
      'Monarch', 'Emperor', 'President', 'Prime', 'Minister', 'General', 'Commander', 'Statesman',
      'Diplomat', 'Ambassador', 'Envoy', 'Delegate', 'Representative', 'Council', 'Assembly', 'Parliament',
      'Senate', 'Congress', 'Charter', 'Declaration', 'Proclamation', 'Edict', 'Decree', 'Law',
      'Statute', 'Code', 'Ordinance', 'Diaspora', 'Exodus', 'Displacement', 'Resettlement', 'Assimilation',
      'Integration', 'Diversity', 'Pluralism', 'Multiculturalism', 'Influence', 'Impact', 'Contribution', 'Achievement',
      'Milestone', 'Landmark', 'Breakthrough', 'Turning', 'Point', 'Feudalism', 'Serfdom', 'Vassalage',
      'Suzerainty', 'Fiefdom', 'Manor', 'Guild', 'Citystate', 'Confederation', 'Federation', 'Commonwealth',
      'Protectorate', 'Mandate', 'Trusteeship', 'Dominion', 'Metropole', 'Hinterland', 'Borderland', 'Hegemony',
      'Suzerain', 'Tributary', 'Vassal', 'Enclave', 'Exclave', 'Partition', 'Unification', 'Secession',
      'Cessation', 'Armistice', 'Ceasefire', 'Capitulation', 'Surrender', 'Reparation', 'Indemnity', 'Garrison',
      'Fortification', 'Rampart', 'Citadel', 'Bastion', 'Stronghold', 'Outpost', 'Militia', 'Conscription',
      'Levy', 'Mercenary', 'Cavalry', 'Infantry', 'Artillery', 'Vanguard', 'Rearguard', 'Flank',
      'Formation', 'Strategy', 'Tactics', 'Logistics', 'Provisioning', 'Blockade', 'Embargo', 'Sanction',
      'Tribute', 'Investiture',
    ],
  },
  {
    id: 'astrophysics-space-exploration',
    label: 'Astrophysics & Space Exploration',
    words: [
      'Rocket', 'Propulsion', 'Thrust', 'Fuel', 'Engine', 'Launch', 'Trajectory', 'Orbit',
      'Satellite', 'Spacecraft', 'Module', 'Capsule', 'Shuttle', 'Station', 'Habitat', 'Lander',
      'Rover', 'Probe', 'Mission', 'Payload', 'Astronaut', 'Cosmonaut', 'Crew', 'Spacewalk',
      'Extravehicular', 'Docking', 'Rendezvous', 'Reentry', 'Splashdown', 'Landing', 'Gravity', 'Microgravity',
      'Weightlessness', 'Acceleration', 'Velocity', 'Escapevelocity', 'Freefall', 'Navigation', 'Guidance', 'Control',
      'Telemetry', 'Communication', 'Signal', 'Transmission', 'Antenna', 'Receiver', 'Groundstation', 'Missioncontrol',
      'Countdown', 'Ignition', 'Liftoff', 'Ascent', 'Stage', 'Booster', 'Separation', 'Fairing',
      'Deployment', 'Insertion', 'Altitude', 'Apogee', 'Perigee', 'Inclination', 'Eccentricity', 'Period',
      'Geostationary', 'Geosynchronous', 'Lowearth', 'Interplanetary', 'Interstellar', 'Voyage', 'Journey', 'Flyby',
      'Gravityassist', 'Slingshot', 'Correction', 'Maneuver', 'Exploration', 'Discovery', 'Reconnaissance', 'Survey',
      'Mapping', 'Imaging', 'Instrument', 'Sensor', 'Camera', 'Spectrometer', 'Analysis', 'Sample',
      'Collection', 'Retrieval', 'Return', 'Colonization', 'Settlement', 'Terraforming', 'Atmosphere', 'Environment',
      'Radiation', 'Shielding', 'Protection', 'Lifesupport', 'Sustainability', 'Resource', 'Utilization', 'Insitu',
      'Planet', 'Moon', 'Asteroid', 'Comet', 'Belt', 'Ring', 'System', 'Exoplanet',
      'Habitable', 'Zone', 'Biosignature', 'Astrobiology', 'Extraterrestrial', 'Life', 'Search', 'Detection',
      'Frequency', 'Telescope', 'Observatory', 'Array', 'Detector', 'Resolution', 'Aperture', 'Wavelength',
      'Spectrum', 'Datum', 'Model', 'Simulation', 'Prediction', 'Calculation', 'Determination', 'Tracking',
      'Agency', 'Program', 'Objective', 'Goal', 'Milestone', 'Achievement', 'Breakthrough', 'Innovation',
      'Engineering', 'Design', 'Testing', 'Prototype', 'Development', 'Manufacturing', 'Assembly', 'Integration',
      'Verification', 'Qualification', 'Certification', 'Reliability', 'Redundancy', 'Safety', 'Riskmanagement', 'Contingency',
      'Failsafe', 'Backup', 'Recovery', 'Budget', 'Funding', 'Cost', 'Investment', 'Partnership',
      'Collaboration', 'International', 'Cooperation', 'Agreement', 'Treaty', 'Legacy', 'Inspiration', 'Education',
      'Outreach', 'Publicengagement', 'Curiosity', 'Wonder', 'Frontier', 'Horizon', 'Future', 'Perturbation',
      'Ephemeris', 'Almanac', 'Occultation', 'Transit', 'Conjunction', 'Opposition', 'Quadrature', 'Elongation',
      'Declination', 'Ascension', 'Latitude', 'Longitude', 'Meridian', 'Equator', 'Pole', 'Precession',
      'Nutation', 'Libration', 'Wobble', 'Spin', 'Rotation', 'Revolution', 'Sidereal', 'Synodic',
      'Tropical', 'Anomalistic', 'Draconic', 'Epoch', 'Reference', 'Frame', 'Ecliptic', 'Equinox',
      'Solstice', 'Perihelion', 'Aphelion', 'Barycenter', 'Massratio', 'Rochelobe', 'Lagrangepoint', 'Haloorbit',
      'Transferorbit', 'Hohmann', 'Bielliptic', 'Aerobraking', 'Aerocapture', 'Parachute', 'Retrorocket', 'Heatshield',
      'Ablation', 'Thermalprotection', 'Cryogenic', 'Propellant', 'Oxidizer', 'Combustion', 'Nozzle', 'Chamber',
      'Turbopump', 'Gimbal', 'Vectoring', 'Staging', 'Cryostat', 'Manifold', 'Regolith', 'Impactcrater',
      'Ejecta', 'Tektite', 'Chondrite', 'Achondrite',
    ],
  },
] as const

export const TOTAL_VERTICAL_WORD_READING_CATEGORIES = VERTICAL_WORD_READING_CATEGORIES.length

export function buildUnitsForCategory(category: VerticalWordReadingCategory): readonly ReadingUnit[] {
  return category.words.map((text, index) => ({ id: `${category.id}-word-${index}`, text }))
}

const LAST_CATEGORY_STORAGE_KEY = 'qsr-vertical-word-reading-last-category'

// Own-copy of the identical non-repeat algorithm every other exercise's
// pickSessionCategory uses (Vertical Chunk Sliding, Flash Recall Sprint,
// Vertical Flash Recall) — client-only, called only from a useEffect in
// the Experience orchestrator, never a lazy useState initializer, so the
// server-rendered 'settings' phase and the client's first paint always
// match before this ever runs.
export function pickSessionCategory(): VerticalWordReadingCategory {
  const categories = VERTICAL_WORD_READING_CATEGORIES
  let lastId: string | null = null
  if (typeof window !== 'undefined') {
    try {
      lastId = localStorage.getItem(LAST_CATEGORY_STORAGE_KEY)
    } catch {
      lastId = null
    }
  }

  const pool = lastId === null ? categories : categories.filter((category) => category.id !== lastId)
  const eligiblePool = pool.length > 0 ? pool : categories
  const picked = eligiblePool[Math.floor(Math.random() * eligiblePool.length)] ?? categories[0]!

  if (typeof window !== 'undefined') {
    try {
      localStorage.setItem(LAST_CATEGORY_STORAGE_KEY, picked.id)
    } catch {
      // Best-effort only — a session still works perfectly without
      // non-repeat tracking, it just can't remember last time's pick.
    }
  }

  return picked
}
