// Number Flash™ Engine — builds SessionItems from the generated number
// dataset. The "challenge logic" is deliberately different from Word
// Flash's: numbers don't have a natural pool of "near-miss real numbers"
// the way word families did, so distractors are generated by perturbing
// the stimulus itself — transposing two adjacent digits, or substituting
// a single digit — never drawn from an unrelated pool and never random
// numbers. This mirrors exactly what a genuinely confusable wrong answer
// looks like for a number: 48291 next to 48219, 48297, 49291 — each
// differs from the original in exactly one small, local way.
//
// Pipeline: Dataset (generated numbers) → Visual Width Validator → pick
// stimuli + perturbation-generated distractors → Typography Engine
// (FitText, via ChoiceGrid/FlashStimulus) → Renderer. Same shape as
// wordFlashEngine.ts's pipeline; the generation step is the only thing
// that's genuinely new.

import type { ContentItem, SessionItem } from '@/types/exercise-engine'
import { shuffleArray, shuffleIndices } from '@/lib/exercise-engine/randomizationEngine'
import { isVisuallyValid } from '@/lib/exercise-engine/visualWidthValidator'

export type NumberFlashItem = {
  text: string
  digitLength: number
}

// Swap two adjacent digits at a seeded position. Returns null when the
// swap would be a no-op (the two digits happen to be identical — a
// degenerate "distractor" identical to the stimulus is worse than no
// candidate at all), or when it would produce a leading zero (swapping
// positions 0 and 1 when digit 1 is '0' — found by a failing test, not
// assumed safe).
function transposeAdjacentDigits(number: string, seed: number): string | null {
  const digits = number.split('')
  if (digits.length < 2) return null
  const pos = shuffleIndices(digits.length - 1, seed)[0]!
  if (digits[pos] === digits[pos + 1]) return null
  if (pos === 0 && digits[1] === '0') return null
  const swapped = [...digits]
  const tmp = swapped[pos]!
  swapped[pos] = swapped[pos + 1]!
  swapped[pos + 1] = tmp
  return swapped.join('')
}

// Substitute a single digit at a seeded position with a different seeded
// digit. Never produces a leading zero (position 0 only draws 1–9), and
// never returns the same digit it started with.
function substituteDigit(number: string, seed: number): string {
  const digits = number.split('')
  const pos = shuffleIndices(digits.length, seed)[0]!
  const currentDigit = digits[pos]!
  const digitRange = pos === 0 ? 9 : 10   // position 0: 1-9, else 0-9
  const digitOffset = pos === 0 ? 1 : 0
  let newDigit = String(digitOffset + shuffleIndices(digitRange, seed + 7919)[0]!)
  let attempt = 1
  while (newDigit === currentDigit && attempt < digitRange) {
    newDigit = String(digitOffset + shuffleIndices(digitRange, seed + 7919 + attempt * 131)[0]!)
    attempt++
  }
  digits[pos] = newDigit
  return digits.join('')
}

// Generate up to 3 distinct, genuinely-confusable distractors for a
// stimulus number. Tries several perturbation strategies with different
// seed offsets and keeps only candidates distinct from the stimulus and
// from each other. May return fewer than 3 for very short numbers with
// limited variety — the caller skips the stimulus rather than pad with a
// weaker or duplicate option.
function generateDistractors(stimulus: string, seed: number): string[] {
  const candidates = new Set<string>()
  const strategies: Array<() => string | null> = [
    () => transposeAdjacentDigits(stimulus, seed),
    () => substituteDigit(stimulus, seed + 1),
    () => substituteDigit(stimulus, seed + 2),
    () => substituteDigit(stimulus, seed + 3),
    () => transposeAdjacentDigits(stimulus, seed + 4),
    () => substituteDigit(stimulus, seed + 5),
  ]
  for (const strategy of strategies) {
    if (candidates.size >= 3) break
    const candidate = strategy()
    if (candidate !== null && candidate !== stimulus) candidates.add(candidate)
  }
  return [...candidates].slice(0, 3)
}

export function buildNumberFlashItems(
  numbers: ContentItem[],
  targetCount: number,
  seed: number,
): SessionItem[] {
  if (numbers.length === 0) return []

  const validNumbers: NumberFlashItem[] = numbers
    .map((n) => ({ text: n.content, digitLength: n.content.length }))
    .filter((number) => isVisuallyValid(number.text, 'option'))

  if (validNumbers.length === 0) return []

  const seen = new Set<string>()
  const uniqueNumbers = validNumbers.filter((number) => {
    if (seen.has(number.text)) return false
    seen.add(number.text)
    return true
  })

  const shuffled = shuffleArray(uniqueNumbers, seed)
  const stimuli = shuffled.slice(0, Math.min(targetCount, shuffled.length))

  const items: SessionItem[] = []

  stimuli.forEach((number, i) => {
    const itemSeed = seed + i * 31337
    const distractors = generateDistractors(number.text, itemSeed)
    if (distractors.length < 3) return

    const options = shuffleArray([number.text, ...distractors], itemSeed)
    const correctIndex = options.indexOf(number.text)

    items.push({
      id: `number-flash-${i}-${itemSeed}`,
      stimulus: number.text,
      stimulusLabel: `Number: ${number.text}`,
      options,
      correctIndex: correctIndex >= 0 ? correctIndex : 0,
      renderAs: 'number',
    })
  })

  return items
}

// ── Reading Speed metrics — Number Flash's own vocabulary ─────────────────

// Brain Performance — recognition throughput expressed as numbers
// recognized per minute, derived from average reaction time. A measure of
// how fast the student recognizes a number once it's visible.
export function computeRecognitionRatePerMinute(averageReactionTimeMs: number): number {
  if (averageReactionTimeMs <= 0) return 0
  return Math.round(60_000 / averageReactionTimeMs)
}

// Estimated Visual Processing Growth — the change in this session's
// accuracy-adjusted recognition rate versus the student's most recent
// prior session. Returns null when there's no prior session — the caller
// renders that as "establishing your baseline," never a fabricated number.
export function computeEstimatedVisualProcessingGrowth(
  currentRatePerMinute: number,
  previousRatePerMinute: number | null,
): number | null {
  if (previousRatePerMinute === null) return null
  return currentRatePerMinute - previousRatePerMinute
}
