// Symbol Flash™ Engine — builds SessionItems from the curated symbol
// dataset, composing groups of 1-3 symbols per the mission's compositional
// difficulty stages. The "challenge logic" here is genuinely new, not
// reused from Word or Number Flash: a stimulus can be a single glyph or a
// small joined group ("# %"), and distractors are generated by perturbing
// exactly one symbol within the group — preferring a visually-confusable
// family swap (★→☆, <→≤) over a random pool symbol, plus reordering for
// multi-symbol groups — never an unrelated random symbol set.
//
// Pipeline: Dataset (curated symbols) → Visual Width Validator → compose
// group + confusable-swap distractors → Typography Engine (FitText, via
// ChoiceGrid/FlashStimulus) → Renderer. Same shape as word/numberFlashEngine.ts.

import type { ContentItem, SessionItem } from '@/types/exercise-engine'
import { pickItems, shuffleArray, shuffleIndices } from '@/lib/exercise-engine/randomizationEngine'
import { isVisuallyValid } from '@/lib/exercise-engine/visualWidthValidator'
import type { SymbolGroupSize } from './symbolFlashDifficulty'

export type SymbolFlashItem = {
  text: string
  family: string | null
}

function readFamily(item: ContentItem): string | null {
  const family = item.metadata?.['family']
  return typeof family === 'string' ? family : null
}

function composeGroup(symbols: SymbolFlashItem[]): string {
  return symbols.map((s) => s.text).join(' ')
}

function pickMixedGroupSize(seed: number): 1 | 2 | 3 {
  const idx = shuffleIndices(3, seed)[0]!
  return (idx + 1) as 1 | 2 | 3
}

// Generates up to 3 distinct distractor groups by perturbing exactly one
// symbol of `group` per candidate — family-confusable swaps first (the
// hardest, most genuinely deceptive tier), then any other pool symbol not
// already in the group, then (for multi-symbol groups) a simple reorder.
// Mirrors wordFlashEngine.ts's family-first-then-fill tiering exactly.
function generateGroupDistractors(group: SymbolFlashItem[], pool: SymbolFlashItem[], seed: number): string[] {
  const originalText = composeGroup(group)
  const familyVariants = new Set<string>()
  const otherVariants = new Set<string>()
  const groupTexts = new Set(group.map((g) => g.text))

  group.forEach((sym, pos) => {
    const familyCandidates = sym.family !== null
      ? pool.filter((p) => p.family === sym.family && p.text !== sym.text)
      : []
    for (const replacement of familyCandidates) {
      const variant = [...group]
      variant[pos] = replacement
      const text = composeGroup(variant)
      if (text !== originalText) familyVariants.add(text)
    }

    const familyTexts = new Set(familyCandidates.map((f) => f.text))
    const otherCandidates = pool.filter((p) => !groupTexts.has(p.text) && !familyTexts.has(p.text))
    for (const replacement of otherCandidates) {
      const variant = [...group]
      variant[pos] = replacement
      const text = composeGroup(variant)
      if (text !== originalText) otherVariants.add(text)
    }
  })

  if (group.length >= 2) {
    const reversed = composeGroup([...group].reverse())
    if (reversed !== originalText) familyVariants.add(reversed)
  }

  const familyPicked = pickItems([...familyVariants], 3, seed)
  if (familyPicked.length >= 3) return familyPicked
  const otherPicked = pickItems([...otherVariants], 3 - familyPicked.length, seed + 99991)
  return [...familyPicked, ...otherPicked]
}

// Builds a session (or one compositional segment of one) of symbol
// SessionItems. `groupSize` is fixed for the call — 1, 2, 3, or 'mixed'
// (each item independently, seeded, picks its own size from 1-3). If the
// pool can't supply 3 distinct distractors for a stimulus, or a duplicate
// group would result, that slot is skipped rather than patched — same
// "never fabricate" guarantee as every other Flash mission.
export function buildSymbolFlashItems(
  symbols: ContentItem[],
  groupSize: SymbolGroupSize,
  targetCount: number,
  seed: number,
): SessionItem[] {
  if (symbols.length === 0) return []

  const validSymbols: SymbolFlashItem[] = symbols
    .map((s) => ({ text: s.content, family: readFamily(s) }))
    .filter((s) => isVisuallyValid(s.text, 'option'))

  const seen = new Set<string>()
  const uniqueSymbols = validSymbols.filter((s) => {
    if (seen.has(s.text)) return false
    seen.add(s.text)
    return true
  })
  if (uniqueSymbols.length === 0) return []

  const items: SessionItem[] = []
  const usedStimuli = new Set<string>()

  for (let i = 0; i < targetCount; i++) {
    const itemSeed = seed + i * 31337
    const thisGroupSize = groupSize === 'mixed' ? pickMixedGroupSize(itemSeed) : groupSize

    let group: SymbolFlashItem[] = []
    let stimulusText = ''
    for (let attempt = 0; attempt < 10; attempt++) {
      const candidateGroup = pickItems(uniqueSymbols, thisGroupSize, itemSeed + attempt * 97)
      if (candidateGroup.length < thisGroupSize) break // pool too small for this group size
      const candidateText = composeGroup(candidateGroup)
      if (!usedStimuli.has(candidateText) && isVisuallyValid(candidateText, 'option')) {
        group = candidateGroup
        stimulusText = candidateText
        break
      }
    }
    if (group.length < thisGroupSize || stimulusText === '') continue

    const distractors = generateGroupDistractors(group, uniqueSymbols, itemSeed)
      .filter((d) => isVisuallyValid(d, 'option'))
    if (distractors.length < 3) continue

    usedStimuli.add(stimulusText)
    const options = shuffleArray([stimulusText, ...distractors], itemSeed)
    const correctIndex = options.indexOf(stimulusText)

    items.push({
      id: `symbol-flash-${i}-${itemSeed}`,
      stimulus: stimulusText,
      stimulusLabel: `Symbol${thisGroupSize > 1 ? ' group' : ''}: ${stimulusText}`,
      options,
      correctIndex: correctIndex >= 0 ? correctIndex : 0,
      renderAs: 'symbol',
    })
  }

  return items
}

// ── Reading Speed metrics — shared framing with Number Flash ─────────────

export function computeRecognitionRatePerMinute(averageReactionTimeMs: number): number {
  if (averageReactionTimeMs <= 0) return 0
  return Math.round(60_000 / averageReactionTimeMs)
}

export function computeEstimatedVisualProcessingGrowth(
  currentRatePerMinute: number,
  previousRatePerMinute: number | null,
): number | null {
  if (previousRatePerMinute === null) return null
  return currentRatePerMinute - previousRatePerMinute
}
