'use server'

import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'

const ClaimSchema = z.object({
  courseId: z.string().uuid(),
})

type ClaimResult = { success: true; token: string } | { success: false; error: string }

export async function claimCertificate(input: unknown): Promise<ClaimResult> {
  const parsed = ClaimSchema.safeParse(input)
  if (!parsed.success) return { success: false, error: 'Invalid request.' }

  const { courseId } = parsed.data
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { success: false, error: 'Not authenticated.' }

  // Idempotent: return existing certificate without re-checking eligibility
  const { data: existing } = await supabase
    .from('certificates')
    .select('token')
    .eq('user_id', user.id)
    .eq('course_id', courseId)
    .single()

  if (existing) return { success: true, token: existing.token }

  // Must be enrolled
  const { data: enrollment } = await supabase
    .from('enrollments')
    .select('id')
    .eq('user_id', user.id)
    .eq('course_id', courseId)
    .single()

  if (!enrollment) {
    return { success: false, error: 'You are not enrolled in this course.' }
  }

  // Fetch published lesson IDs for this course
  const { data: lessonRows } = await supabase
    .from('lessons')
    .select('id')
    .eq('course_id', courseId)
    .eq('is_published', true)

  const lessonIds = (lessonRows ?? []).map((l) => l.id)

  if (lessonIds.length === 0) {
    return { success: false, error: 'No published lessons in this course.' }
  }

  // Count how many the user has completed
  const { count: completedCount } = await supabase
    .from('lesson_completions')
    .select('*', { count: 'exact', head: true })
    .eq('user_id', user.id)
    .in('lesson_id', lessonIds)

  if ((completedCount ?? 0) < lessonIds.length) {
    return {
      success: false,
      error: 'You have not completed all lessons yet.',
    }
  }

  // Issue certificate (token generated by DB default)
  const { data: cert, error } = await supabase
    .from('certificates')
    .insert({ user_id: user.id, course_id: courseId })
    .select('token')
    .single()

  if (error !== null || !cert) {
    // Race condition: another request issued it — re-fetch
    if (error?.code === '23505') {
      const { data: retry } = await supabase
        .from('certificates')
        .select('token')
        .eq('user_id', user.id)
        .eq('course_id', courseId)
        .single()
      if (retry) return { success: true, token: retry.token }
    }
    return { success: false, error: 'Failed to issue certificate.' }
  }

  return { success: true, token: cert.token }
}
