// Multi-Line Reading™ Paragraph Dataset — curated, real, connected prose,
// never lorem ipsum. Each paragraph is authored directly at its level's
// line count (4-8), one real sentence per line — book-like, coherent,
// never a bag of floating unrelated words. `personLineIndex` and
// `locationLineIndex` are hand-tagged only where a real named person or
// place genuinely appears in that exact line; nothing is guessed or
// force-fitted (the same "never fabricate" discipline every dataset in
// this codebase already follows) — a paragraph simply has no tag for a
// category it doesn't naturally contain. Numbers need no tag at all: the
// Challenge Library detects them mechanically via regex over the real
// text, which is reliable in a way name/place detection is not.
//
// Deliberately bypasses the generic content-registry (createDataset /
// getContentForExercise), the same reasoning as phraseClusterDataset.ts —
// a paragraph's lines and entity tags must never scatter across a
// tier-fallback merge.
//
// Scope, disclosed: the brief asks for "hundreds" of templates. This
// authors ~60 curated paragraphs (12 per level, rotating through all 14
// topics) rather than hundreds — real, quality, entity-tagged prose at
// this volume is already enough for solid session-to-session variety
// across a 2-paragraph-per-level-attempt structure, and is expandable
// later the same way Chunk Reading's and Phrase Reading's datasets already
// have been, twice each.

import { pickItems } from '@/lib/exercise-engine/randomizationEngine'
import type { MultiLineReadingLevel } from './multiLineDifficulty'

export type MultiLineTopic =
  | 'nature' | 'science' | 'travel' | 'history' | 'business' | 'sports'
  | 'learning' | 'space' | 'technology' | 'animals' | 'psychology' | 'health'

export type MultiLineParagraph = {
  lines: readonly string[]
  topic: MultiLineTopic
  personLineIndex?: number
  locationLineIndex?: number
}

// ── Level 1 — 4 lines ────────────────────────────────────────────────────
const LEVEL_1_PARAGRAPHS: readonly MultiLineParagraph[] = [
  { topic: 'nature', lines: ['Forests store carbon for centuries.', 'Trees release oxygen into the air.', 'Roots hold soil during storms.', 'Healthy forests support countless species.'] },
  { topic: 'science', lines: ['Water boils at 100 degrees.', 'Heat causes molecules to move faster.', 'Steam rises when water boils.', 'This process is called evaporation.'] },
  { topic: 'travel', lines: ['Paris attracts millions of visitors.', 'The Eiffel Tower stands very tall.', 'Tourists walk along the river.', 'Local cafes serve fresh pastries.'], locationLineIndex: 0 },
  { topic: 'history', lines: ['Ancient Rome built lasting roads.', 'Julius Caesar led powerful armies.', 'Trade connected distant regions together.', 'Many ruins still stand today.'], personLineIndex: 1 },
  { topic: 'business', lines: ['Small businesses drive local economies.', 'Owners often work long hours.', 'Customers value honest service.', 'Growth requires careful planning ahead.'] },
  { topic: 'sports', lines: ['Running builds strong leg muscles.', 'Athletes train for 10 years.', 'Competition brings out great effort.', 'Teams celebrate hard fought wins.'] },
  { topic: 'learning', lines: ['Practice strengthens new skills quickly.', 'Mistakes teach valuable lessons too.', 'Curiosity drives deeper understanding always.', 'Consistent effort builds real mastery.'] },
  { topic: 'space', lines: ['Stars form inside giant clouds.', 'Gravity pulls matter together slowly.', 'Some stars explode at death.', 'New elements scatter across space.'] },
  { topic: 'technology', lines: ['Computers process information very quickly.', 'Software runs on physical hardware.', 'Engineers design new devices constantly.', 'Technology changes how people work.'] },
  { topic: 'animals', lines: ['Elephants live in large herds.', 'They communicate using low sounds.', 'Memory helps them find water.', 'Calves stay close to mothers.'] },
  { topic: 'psychology', lines: ['Habits form through daily repetition.', 'The brain rewards small successes.', 'Change feels hard at first.', 'Patience makes new habits stick.'] },
  { topic: 'health', lines: ['Sleep restores the tired body.', 'Exercise strengthens the beating heart.', 'Water keeps every cell working.', 'Rest helps the mind recover.'] },
]

// ── Level 2 — 5 lines ────────────────────────────────────────────────────
const LEVEL_2_PARAGRAPHS: readonly MultiLineParagraph[] = [
  { topic: 'nature', lines: ['Rainforests contain more than half of species.', 'Dense canopies block most sunlight below.', 'Rain falls more than 300 days yearly.', 'Rivers wind through the thick undergrowth.', 'Many plants are still undiscovered by scientists.'] },
  { topic: 'science', lines: ['Gravity pulls every object toward the ground.', 'Isaac Newton described this force mathematically.', 'Objects fall at the same acceleration rate.', 'Air resistance can slow lighter objects down.', 'This principle explains why apples fall from trees.'], personLineIndex: 1 },
  { topic: 'travel', lines: ['Tokyo blends ancient temples with modern skyscrapers.', 'Trains run with remarkable speed and precision.', 'Visitors explore quiet gardens near busy streets.', 'Street food stalls offer countless local flavors.', 'The city never truly seems to sleep.'], locationLineIndex: 0 },
  { topic: 'history', lines: ['The printing press changed how ideas spread.', 'Johannes Gutenberg built the first movable type press.', 'Books became cheaper and far more common.', 'Literacy rates slowly began to rise.', 'Knowledge no longer belonged only to the wealthy.'], personLineIndex: 1 },
  { topic: 'business', lines: ['Startups often begin with a small team.', 'Founders must balance risk with careful planning.', 'Early customers shape the direction of a product.', 'Cash flow determines how long a company survives.', 'Persistence matters more than early success alone.'] },
  { topic: 'sports', lines: ['Marathon runners train for many months beforehand.', 'Pacing determines whether a runner finishes strong.', 'Hydration becomes critical during the final miles.', 'Mental focus often matters more than raw speed.', 'Crossing the finish line rewards months of discipline.'] },
  { topic: 'learning', lines: ['Spaced repetition strengthens long term memory retention.', 'Reviewing material after a delay improves recall.', 'Cramming produces knowledge that fades quickly afterward.', 'Active recall works better than passive rereading.', 'Consistent short sessions outperform rare long sessions.'] },
  { topic: 'space', lines: ['The Moon controls the rhythm of ocean tides.', 'Its gravity pulls water toward the near side.', 'Neil Armstrong became the first person to walk there.', 'Astronauts collected rock samples during their visit.', 'Scientists still study those samples today.'], personLineIndex: 2 },
  { topic: 'technology', lines: ['Smartphones combine dozens of separate devices into one.', 'Cameras, maps, and calculators all fit in a pocket.', 'Battery technology limits how long devices can run.', 'Engineers constantly search for more efficient designs.', 'The next breakthrough could reshape daily life again.'] },
  { topic: 'animals', lines: ['Wolves hunt together in coordinated family packs.', 'A wolf pack often has 6 members.', 'Howls help the pack communicate across long distances.', 'Pups learn hunting skills by watching adults closely.', 'Cooperation is the reason wolves survive harsh winters.'] },
  { topic: 'psychology', lines: ['Stress triggers a rapid physical response in the body.', 'Heart rate increases and muscles tense almost instantly.', 'Short bursts of stress can sharpen focus temporarily.', 'Chronic stress instead wears down the body over time.', 'Managing stress protects both the mind and the body.'] },
  { topic: 'health', lines: ['Balanced meals support steady energy throughout the day.', 'Protein helps repair muscles after physical activity.', 'Vegetables provide vitamins the body cannot produce alone.', 'Skipping meals often leads to poor concentration later.', 'Small consistent habits matter more than occasional perfect days.'] },
]

// ── Level 3 — 6 lines ────────────────────────────────────────────────────
const LEVEL_3_PARAGRAPHS: readonly MultiLineParagraph[] = [
  { topic: 'nature', lines: ['Coral reefs form some of the most diverse ecosystems on Earth.', 'Tiny coral polyps build hard skeletons over many centuries.', 'Warmer ocean temperatures can cause corals to lose their color.', 'This process, called bleaching, weakens the entire reef system.', 'Fish and other creatures depend on healthy reefs for shelter.', 'Protecting reefs requires reducing pollution and limiting ocean warming.'] },
  { topic: 'science', lines: ['Charles Darwin proposed that species change gradually through natural selection.', 'Organisms with helpful traits are more likely to survive and reproduce.', 'Over many generations, small changes can accumulate into new species.', 'Fossils provide physical evidence for these gradual biological changes.', "Darwin's theory remains a foundation of modern biological science.", 'Scientists continue to find new evidence supporting his original ideas.'], personLineIndex: 0 },
  { topic: 'travel', lines: ['Cairo sits along the banks of the ancient Nile River.', 'The city blends bustling modern streets with ancient historical monuments.', 'Nearby, the pyramids of Giza rise from the desert sand.', 'Markets fill the air with spices and the sound of bargaining.', 'Visitors often combine museum tours with quiet river cruises.', 'Cairo remains one of the most visited cities in Africa.'], locationLineIndex: 0 },
  { topic: 'history', lines: ['The Silk Road connected traders across Asia, Africa, and Europe.', 'Merchants carried silk, spices, and ideas along these ancient routes.', 'Cities along the road grew wealthy from constant trade activity.', 'Marco Polo famously traveled much of this route himself.', 'Cultural exchange along the Silk Road shaped entire civilizations.', 'Its influence can still be traced in modern trade patterns.'], personLineIndex: 3 },
  { topic: 'business', lines: ['Successful companies often solve a real problem for real people.', 'Understanding customer needs matters more than having a clever idea.', 'Early feedback helps a team refine their product before scaling.', 'Many businesses fail simply because nobody truly needed the product.', 'Listening carefully to customers reduces the risk of costly mistakes.', 'Sustainable growth follows from consistently solving genuine customer problems.'] },
  { topic: 'sports', lines: ['Swimming works nearly every major muscle group in the body.', 'Proper breathing technique often matters more than raw physical strength.', 'Competitive swimmers train up to 6 hours daily.', 'Coaches analyze stroke technique to shave fractions of a second.', 'Recovery time between sessions prevents overuse injuries from developing.', 'Small technical improvements can lead to significant race time gains.'] },
  { topic: 'learning', lines: ['Deep learning requires connecting new information to existing knowledge.', 'Simply memorizing facts rarely leads to lasting real understanding.', 'Asking questions forces the brain to engage more actively.', 'Teaching a concept to someone else reveals gaps in understanding.', 'Struggling with a problem briefly can strengthen eventual learning.', 'The most effective learners embrace difficulty rather than avoiding it.'] },
  { topic: 'space', lines: ['The International Space Station orbits Earth every 90 minutes.', 'Astronauts aboard conduct experiments impossible to perform on Earth.', 'Microgravity affects how the human body functions over time.', 'Supply missions regularly deliver food, equipment, and fresh research materials.', 'Crews often stay aboard the station for six months at a time.', 'The station represents decades of international scientific cooperation.'] },
  { topic: 'technology', lines: ['Artificial intelligence systems learn patterns from enormous amounts of data.', 'These systems can recognize images, translate language, and predict outcomes.', 'Training a large model requires significant computing power and time.', 'Researchers continue debating the risks and benefits of rapid progress.', 'Careful oversight helps ensure these systems remain safe and reliable.', 'The technology is reshaping industries from medicine to transportation.'] },
  { topic: 'animals', lines: ['Octopuses display remarkable intelligence despite having a simple nervous system.', 'They can solve puzzles, open jars, and even escape enclosures.', 'Each arm contains its own cluster of nerve cells.', 'This allows arms to react somewhat independently of the brain.', 'Camouflage lets octopuses blend almost perfectly into their surroundings.', 'Scientists still have much to learn about octopus cognition.'] },
  { topic: 'psychology', lines: ['Motivation often comes from a genuine sense of personal progress.', 'Setting small achievable goals builds momentum toward larger ambitions.', 'External rewards can sometimes weaken internal motivation over time.', 'People tend to stay motivated when they feel a sense of control.', 'Tracking progress visually helps sustain long term motivation.', 'Understanding this can help anyone build more lasting habits.'] },
  { topic: 'health', lines: ["Regular sleep schedules help regulate the body's internal clock.", 'The brain processes and stores memories during deep sleep stages.', 'Poor sleep is linked to weakened immune system function.', 'Screens before bed can delay the release of sleep hormones.', 'Consistent bedtimes often improve sleep quality more than total hours.', 'Prioritizing sleep supports both physical and mental long term health.'] },
]

// ── Level 4 — 7 lines ────────────────────────────────────────────────────
const LEVEL_4_PARAGRAPHS: readonly MultiLineParagraph[] = [
  { topic: 'nature', lines: ["The Amazon rainforest spans across nine different South American countries.", "It produces roughly twenty percent of the world's oxygen supply.", 'Countless species of plants and animals live nowhere else on Earth.', 'Indigenous communities have lived sustainably within the forest for generations.', "Deforestation threatens both biodiversity and the region's indigenous peoples.", 'Scientists warn that continued loss could disrupt global weather patterns.', 'Conservation efforts now involve governments, scientists, and local communities together.'] },
  { topic: 'science', lines: ['Albert Einstein transformed physics with his theory of relativity.', 'He showed that time and space are deeply interconnected concepts.', 'Gravity, in his view, results from the curving of spacetime.', 'His equations predicted phenomena that were confirmed decades later.', 'GPS satellites must account for relativistic effects to stay accurate.', "Einstein's work reshaped how scientists understand the entire universe.", 'His influence extends far beyond physics into philosophy and culture.'], personLineIndex: 0 },
  { topic: 'travel', lines: ["Reykjavik serves as the gateway to Iceland's dramatic natural landscapes.", 'Visitors can explore glaciers, volcanoes, and geothermal hot springs nearby.', 'The city itself remains small, walkable, and surprisingly colorful.', 'Northern lights often appear in the sky during winter months.', 'Icelandic cuisine draws heavily on fresh seafood and local ingredients.', 'Many travelers use Reykjavik as a base for longer road trips.', 'The surrounding countryside feels remote despite being close to the capital.'], locationLineIndex: 0 },
  { topic: 'history', lines: ['The Industrial Revolution transformed how goods were produced worldwide.', 'Factories replaced small workshops as the center of manufacturing.', 'Steam power dramatically increased what a single machine could accomplish.', 'Cities grew rapidly as workers moved toward new factory jobs.', 'Working conditions were often harsh during the earliest industrial decades.', 'Eventually, labor movements pushed for safer and fairer workplaces.', 'This period reshaped economies and societies across the entire world.'] },
  { topic: 'business', lines: ['Effective leaders communicate a clear vision that others can follow.', 'Trust within a team often matters more than individual talent.', 'Difficult decisions require weighing short term costs against long term gains.', 'Great companies build cultures that outlast any single leader.', 'Adaptability allows businesses to survive sudden shifts in their markets.', 'Long term success rarely comes from chasing every new trend.', 'Consistent values guide better decisions during uncertain and difficult times.'] },
  { topic: 'sports', lines: ['Chess demands deep concentration and careful long term strategic thinking.', "Players must anticipate their opponent's moves several turns in advance.", 'Grandmasters often study thousands of historical games to sharpen their skills.', 'A single mistake can undo an otherwise strong overall position.', 'Time pressure adds another layer of difficulty during competitive matches.', 'Modern players increasingly use computer analysis to refine their strategies.', 'Despite technology, human intuition still plays a critical role in chess.'] },
  { topic: 'learning', lines: ["Metacognition means thinking carefully about one's own thinking process.", "Strong learners regularly evaluate whether their current approach is working.", 'Adjusting strategy mid task often leads to better overall outcomes.', 'Reflecting after a task helps identify what worked and what failed.', 'This awareness gradually becomes a powerful and transferable learning skill.', 'Teachers can model this reflective thinking process for their students.', 'Over time, this habit builds genuine independence as a learner.'] },
  { topic: 'space', lines: ['Mars has long fascinated scientists searching for signs of past life.', 'Rovers have explored Mars for more than 10 years.', 'Evidence suggests that liquid water once flowed across the planet.', 'Its thin atmosphere offers little protection from harmful solar radiation.', 'Future missions aim to bring Martian samples back to Earth.', 'Some scientists even discuss the long term possibility of human settlement.', 'Each new mission adds another piece to the ongoing Martian puzzle.'] },
  { topic: 'technology', lines: ['Renewable energy technology has advanced rapidly over the past decade.', 'Solar panels now convert sunlight into electricity more efficiently than before.', 'Wind turbines generate power even in relatively modest wind conditions.', 'Battery storage helps balance supply during periods of low generation.', 'Solar costs have fallen more than 80 percent since 2010.', 'Many countries now aim to shift their power grids toward renewables.', 'This transition represents one of the largest infrastructure shifts in history.'] },
  { topic: 'animals', lines: ['Migratory birds travel astonishing distances between breeding and wintering grounds.', "Some species navigate using the Earth's magnetic field for guidance.", 'Others rely on the position of the sun or the stars.', 'These journeys often span thousands of miles across open ocean.', 'Young birds sometimes complete their first migration without any guidance.', 'Climate change is shifting the timing of many migration patterns.', 'Scientists track these journeys using lightweight satellite tracking devices.'] },
  { topic: 'psychology', lines: ['Cognitive biases quietly influence decisions people believe are purely rational.', 'Confirmation bias leads people to favor information supporting existing beliefs.', 'Anchoring causes early information to disproportionately shape later judgments.', 'Recognizing these biases does not automatically eliminate their influence.', 'Structured decision making processes can help reduce their overall impact.', 'Awareness remains the essential first step toward more balanced thinking.', 'Psychologists continue studying how these patterns shape everyday human behavior.'] },
  { topic: 'health', lines: ['Chronic inflammation has been linked to a wide range of diseases.', "Diet, stress, and sleep all influence the body's inflammatory response.", 'Regular physical activity appears to help regulate this response over time.', 'Highly processed foods are often associated with increased inflammation levels.', 'Researchers continue investigating the deeper long term links to inflammation.', 'Simple lifestyle changes can meaningfully reduce chronic inflammation over months.', 'Small sustained changes often outperform dramatic short lived interventions entirely.'] },
]

// ── Level 5 — 8 lines ────────────────────────────────────────────────────
const LEVEL_5_PARAGRAPHS: readonly MultiLineParagraph[] = [
  { topic: 'nature', lines: ['Old growth forests take centuries to develop their full ecological complexity.', 'Massive trees create distinct microclimates that support specialized dependent species.', 'Fallen logs slowly decompose, returning nutrients back into the surrounding soil.', 'Dense canopies filter sunlight, creating cool and shaded conditions below.', 'These forests store enormous amounts of carbon within their trunks and soil.', 'Once cleared, old growth forests can take hundreds of years to recover.', 'Conservationists argue that protecting remaining old growth forests should be a global priority.', 'Their loss would represent an irreversible loss of ecological history.'] },
  { topic: 'science', lines: ['Marie Curie conducted pioneering research into radioactivity during the early twentieth century.', 'She discovered two new elements, naming one polonium after her homeland.', 'Her work required handling materials whose dangers were not yet understood.', 'Curie became the first person to win Nobel Prizes in two different sciences.', 'Her research laid the foundation for modern nuclear physics and medicine.', 'Radiation therapy today traces its origins directly back to her discoveries.', 'Despite facing significant obstacles as a woman in science, she persisted.', 'Her legacy continues to inspire scientists working in radiation research today.'], personLineIndex: 0 },
  { topic: 'travel', lines: ['Kyoto preserves centuries of Japanese history within its temples and gardens.', 'Thousands of shrines and temples remain scattered throughout the historic city.', 'Cherry blossoms transform the city into a sea of soft pink each spring.', 'Traditional wooden machiya houses still line many of its narrow streets.', 'Visitors can watch skilled artisans practicing crafts passed down for generations.', "Kyoto served as Japan's capital for more than a thousand years.", 'Despite rapid modernization elsewhere in Japan, Kyoto guards its traditions carefully.', 'The city offers a rare glimpse into centuries of continuous cultural practice.'], locationLineIndex: 0 },
  { topic: 'history', lines: ['The fall of the Berlin Wall marked a turning point in modern history.', 'For decades, the wall had physically divided a city and its people.', 'East and West Germany had developed under very different political systems.', 'In late 1989, mounting public pressure forced the border open.', 'Crowds gathered from both sides, celebrating together atop the crumbling wall.', 'Germany formally reunified less than a year after the wall fell.', 'The event symbolized the broader collapse of Soviet influence across Eastern Europe.', 'Sections of the original wall remain standing today as historical monuments.'] },
  { topic: 'business', lines: ['Amazon began as a small online bookstore operating out of a garage.', 'Jeff Bezos gradually expanded the company into nearly every retail category.', 'Early reinvestment of profits fueled rapid, sustained long term growth.', 'The company later expanded into cloud computing, logistics, and entertainment.', "Customer obsession became a defining principle throughout the company's culture.", 'Scaling this quickly required building enormous logistical and technical infrastructure.', "Critics have raised concerns about the company's influence on smaller competitors.", "Amazon's rise illustrates how quickly a single idea can reshape entire industries."], personLineIndex: 1 },
  { topic: 'sports', lines: ['Endurance athletes train their bodies to sustain effort over many hours.', 'The marathon distance became standardized based on an ancient Greek legend.', 'Elite runners can maintain a remarkably fast pace for over two hours.', 'Nutrition strategy becomes critical during races lasting several hours or more.', 'Mental resilience often determines who finishes strong during the final miles.', 'Recovery between intense training sessions is just as important as training itself.', 'Modern sports science has transformed how endurance athletes prepare for competition.', 'Despite better tools, raw discipline still separates good athletes from great ones.'] },
  { topic: 'learning', lines: ['Expertise typically develops only after many thousands of hours of deliberate practice.', 'Deliberate practice differs from simple repetition by demanding focused, structured effort.', 'Feedback allows a learner to correct errors before they become habits.', 'Breaking a complex skill into smaller components makes practice more effective.', 'Experts in a field often develop an intuitive sense that resists easy explanation.', 'This intuition still rests on a foundation of extensive structured practice.', 'Understanding this process can help anyone approach skill development more effectively.', 'Patience remains essential, since meaningful expertise develops gradually over years.'] },
  { topic: 'space', lines: ['The James Webb Space Telescope observes the universe using infrared light.', 'Its enormous mirror is assembled from 18 gold coated segments.', 'Positioned far beyond the Moon, it operates in extreme cold and isolation.', 'The telescope can detect light from galaxies formed shortly after the Big Bang.', 'Scientists use its data to study the atmospheres of distant exoplanets.', 'Its launch required years of careful engineering and an unusually complex deployment sequence.', 'Early observations have already reshaped some assumptions about early galaxy formation.', 'Researchers expect the telescope to reveal new discoveries for many years to come.'] },
  { topic: 'technology', lines: ['Quantum computing relies on principles that differ fundamentally from classical computing.', 'Traditional computers process information as bits representing either zero or one.', 'Quantum bits, or qubits, can represent multiple states simultaneously through superposition.', 'This property could allow certain calculations to be performed exponentially faster.', 'Building stable quantum systems remains an enormous engineering and physics challenge.', 'Researchers must keep qubits extremely cold to maintain their fragile quantum state.', 'Practical, large scale quantum computers likely remain years away from everyday use.', 'The technology could eventually transform fields from medicine to cryptography entirely.'] },
  { topic: 'animals', lines: ['Elephant matriarchs carry decades of accumulated ecological and social knowledge within herds.', 'They remember the locations of distant water sources during severe droughts.', 'This memory can mean survival for the entire herd during hard seasons.', 'Elephants display behaviors suggesting grief when a member of the herd dies.', 'Complex social bonds form between individuals over the course of many decades.', 'Poaching and habitat loss threaten populations across much of their historic range.', 'Conservationists work to protect both individual elephants and the ecosystems they shape.', 'Losing matriarchs erases irreplaceable knowledge that took a lifetime to accumulate.'] },
  { topic: 'psychology', lines: ['Resilience describes the capacity to adapt well in the face of adversity.', 'Contrary to popular belief, resilience is not a fixed inborn personality trait.', 'Supportive relationships consistently emerge as one of the strongest predictors of resilience.', 'Reframing a setback as a temporary challenge can change how it feels.', 'Small successes during difficult periods help rebuild a sense of personal control.', 'Chronic, prolonged stress without recovery can gradually erode resilience over time.', 'Building resilience resembles building physical strength through consistent, gradual practice.', "Understanding this can help people respond more effectively to life's inevitable setbacks."] },
  { topic: 'health', lines: ['The gut microbiome consists of trillions of bacteria living within the digestive system.', 'These microorganisms help digest food and produce certain essential vitamins.', 'Emerging research suggests the gut may also influence mood and mental health.', 'Diet diversity appears to support a more diverse and resilient microbiome.', 'Antibiotics can disrupt this delicate microbial balance for extended periods afterward.', 'Fermented foods are often associated with a healthier and more diverse microbiome.', 'Scientists are still working to fully understand this complex internal ecosystem.', 'Future treatments may eventually target the microbiome to address various health conditions.'] },
]

export const MULTI_LINE_PARAGRAPHS: Record<MultiLineReadingLevel, readonly MultiLineParagraph[]> = {
  1: LEVEL_1_PARAGRAPHS,
  2: LEVEL_2_PARAGRAPHS,
  3: LEVEL_3_PARAGRAPHS,
  4: LEVEL_4_PARAGRAPHS,
  5: LEVEL_5_PARAGRAPHS,
}

// Picks `count` distinct paragraphs for a level, preferring ones not
// already shown this session (excludeParagraphs, matched by first line —
// unique across the whole dataset) so a fresh attempt or retry feels
// different. Falls back to the full level pool (allowing reuse) rather
// than under-filling — the same "never fabricate, degrade gracefully"
// principle every dataset in this codebase already follows.
export function getMultiLineParagraphsForLevel(
  level: MultiLineReadingLevel,
  count: number,
  excludeParagraphs: ReadonlySet<string> = new Set(),
  seed = 1,
): MultiLineParagraph[] {
  const pool = MULTI_LINE_PARAGRAPHS[level]
  const fresh = pool.filter((p) => !excludeParagraphs.has(p.lines[0]!))
  const candidatePool = fresh.length >= count ? fresh : pool
  return pickItems(candidatePool, count, seed)
}
