import type { ReadingUnit } from '@/features/reading-engine/types'

// Paragraph Reading Mode™ dataset — Quantum Speed Reading™ V2, Master
// Reading Engine mode #4. Deliberately its own folder/content, separate
// from the unrelated, protected V1 "Paragraph Reading™" mission-gated
// exercise (src/features/quantum-speed-reading/components/
// ParagraphReadingExperience.tsx) — no shared files, no route collision.
//
// True Multi-Line Comfort Window Sprint — replaces the earlier 8 short
// paragraphs (each ~30-95 words, only 3-8 lines) with 5 genuinely long,
// single-topic passages (~190-210 words each, ~15-20 lines at a
// comfortable reading width) — real, hand-written prose (no AI, no lorem
// ipsum), each one a self-contained short essay on a single idea, matching
// this project's existing reading/focus/growth/patience register. Each
// passage is still exactly one ReadingUnit — the "block" for the
// Comprehension Checkpoint system — but the *engine* now paces through it
// word-by-word (see ParagraphReadingModeBlockRuntime.tsx), not as one
// solid dwell block, so a moving highlight can track real reading
// progress across a passage this long.
const PARAGRAPH_READING_MODE_PASSAGES: readonly string[] = [
  'Most people believe strong readers are simply born that way, gifted with some invisible talent the rest of us missed out on. It is a comforting story, because it excuses the slow, unglamorous work that actually produces the skill. Look closely at anyone who reads well today and you will almost always find the same quiet history: years of ordinary practice, most of it unremarkable, none of it dramatic. They stumbled over long sentences the same way everyone does at first. They lost their place, reread paragraphs twice, and occasionally gave up on a book entirely. What separated them was not raw ability but repetition, the willingness to keep returning to the page even when progress felt invisible. Talent, if it exists at all, only ever decides how a person starts, never how far they eventually go. Consistency does that work instead, one ordinary session at a time, long after any initial excitement has faded into simple habit. This is, in a strange way, encouraging news. It means the skill is not reserved for a lucky few. It means anyone willing to sit with a page a little longer than feels comfortable, day after unremarkable day, can eventually become the kind of reader other people quietly assume was always gifted.',
  'A reading session rarely fails because the material is too difficult. More often, it fails quietly, worn down by a dozen small interruptions the reader barely notices happening. A phone buzzes once, is glanced at, and an entire paragraph disappears from memory before the eyes even finish the page. Real focus does not usually arrive through willpower alone. It arrives because the space around the reader stops asking for attention in the first place. A closed door matters more than most people admit. So does silence, or at least a steady, unremarkable kind of background sound that never demands to be noticed. Good lighting matters too, not for comfort alone but because eyes that are working hard to see clearly have little patience left over for the sentence in front of them. None of this requires anything expensive or elaborate. It requires deciding, before opening the book, that the next twenty minutes belong entirely to the page and nothing else. Readers who protect this small, boring ritual consistently retain more, finish more, and enjoy the process more than readers relying on discipline to fight through constant noise. The environment, quietly arranged in advance, ends up doing far more work than any burst of last-minute concentration ever could.',
  'It sounds like a contradiction: reading more slowly in order to become, eventually, a faster reader. Yet this is almost exactly how real fluency develops. A reader who rushes through difficult material is not actually reading it, not in any meaningful sense. They are scanning shapes, collecting a vague impression, and quietly hoping enough of it sticks. That impression rarely survives contact with a real question about what the passage meant. Slowing down, deliberately, allows the mind to do something rushing never permits: to notice how ideas connect, where an argument shifts direction, which sentence quietly depends on the one before it. This is the same skill, practiced patiently, that later makes fast reading possible at all. Speed without comprehension is not a shortcut; it is simply skipping the step where real understanding gets built. Readers who spend real time at a comfortable, unhurried pace early on tend to develop stronger instincts for structure and meaning, instincts that eventually let them move through familiar material far more quickly than someone who never slowed down long enough to learn what to look for. The paradox resolves itself with practice: patience now becomes speed later, earned honestly rather than forced prematurely.',
  'Two readers can spend the exact same number of hours with books over a year and end up in very different places. One reads intensely for a week, disappears for a month, then returns for another short burst of enthusiasm before drifting away again. The other reads modestly but daily, sometimes for only ten unremarkable minutes, never missing more than a day or two in a row. Despite reading less in any single sitting, the second reader almost always ends up understanding more, retaining more, and enjoying the process more deeply. Consistency changes how the mind treats information. A daily habit signals, quietly but repeatedly, that this material matters enough to return to, and the brain responds by holding onto it more securely between sessions. Intensity, by contrast, produces a brief flood of information with no reliable structure holding it in place afterward, and most of it fades within days. This is not an argument against occasionally reading longer or with more enthusiasm. It is simply a reminder that the small, boring, repeated choice to return to the page tomorrow does more long-term work than any single ambitious weekend ever could. Expertise accumulates quietly, in ordinary sessions, far more often than it arrives all at once.',
  'The most valuable part of reading often happens after the page has already been turned, in the quiet moment where the mind checks a new idea against everything it already believes. Readers who skip this step move quickly but retain very little, since information that is never questioned rarely becomes genuine understanding. Pausing to ask a simple question, does this match what I already know, does it change anything, does it raise a question I cannot yet answer, turns reading into something closer to a real conversation than a one-directional flow of words. This does not need to be a formal exercise. A few seconds of honest reflection between paragraphs is often enough to convert a passing impression into something that survives the following week. Readers who never pause this way often describe finishing a book and immediately struggling to explain what it was actually about, despite having technically read every page. The words were seen, but never truly met with any response. Treating a text as a conversation, rather than a delivery of information, is a small shift in attitude that changes almost everything about how much of it is remembered afterward, and how much genuine understanding a reader carries away once the book itself is closed.',
]

export const PARAGRAPH_READING_MODE_UNITS: readonly ReadingUnit[] = PARAGRAPH_READING_MODE_PASSAGES.map((text, index) => ({
  id: `passage-${index}`,
  text,
}))

export const TOTAL_PARAGRAPH_READING_MODE_UNITS = PARAGRAPH_READING_MODE_UNITS.length
