// Chunk Reading Dataset™ — curated, independently meaningful 2–6 word chunks.
// Each chunk IS the stimulus directly; nothing is mechanically split from a
// longer sentence. Word count is the difficulty axis, matching
// CHUNK_DIFFICULTY_PROFILES exactly (beginner=2 … expert=6; elite/master
// share expert's 6-word pool via the difficulty-tier fallback already built
// into datasetEngine.ts — no dedicated elite/master content needed).
// contentType is 'chunk', not 'phrase' or 'sentence' — a dedicated lane so
// this pool never merges with Phrase Reading's complete-sentence pool (or
// vice versa) at query time. Themed: education, neuroscience, reading,
// memory, focus, learning, psychology.
//
// Expanded (24 items/tier, up from 8) for Progressive Chunk Reading™, whose
// block-based sessions draw more chunks per sitting than the original
// flash-and-choose Chunk Reading exercise — this pool is shared by both,
// read-only from each; neither exercise is modified by the other's needs.

import { createDataset } from '@/lib/exercise-engine/contentEngine'

export const CHUNK_READING_DATASET = createDataset({
  id: 'en-chunk-reading-chunks',
  locale: 'en',
  contentType: 'chunk',
  rawItems: [
    // 2 words — beginner
    { content: 'mental clarity', difficulty: 'beginner', categories: ['focus'] },
    { content: 'reading speed', difficulty: 'beginner', categories: ['reading'] },
    { content: 'visual attention', difficulty: 'beginner', categories: ['reading', 'focus'] },
    { content: 'brain training', difficulty: 'beginner', categories: ['memory'] },
    { content: 'deep focus', difficulty: 'beginner', categories: ['focus'] },
    { content: 'working memory', difficulty: 'beginner', categories: ['memory'] },
    { content: 'rapid learning', difficulty: 'beginner', categories: ['reading'] },
    { content: 'effective reading', difficulty: 'beginner', categories: ['reading'] },
    { content: 'calm mind', difficulty: 'beginner', categories: ['focus'] },
    { content: 'sharp focus', difficulty: 'beginner', categories: ['focus'] },
    { content: 'quick recall', difficulty: 'beginner', categories: ['memory'] },
    { content: 'steady practice', difficulty: 'beginner', categories: ['focus'] },
    { content: 'clear thinking', difficulty: 'beginner', categories: ['focus'] },
    { content: 'active learning', difficulty: 'beginner', categories: ['reading'] },
    { content: 'strong memory', difficulty: 'beginner', categories: ['memory'] },
    { content: 'focused reading', difficulty: 'beginner', categories: ['reading', 'focus'] },
    { content: 'mental strength', difficulty: 'beginner', categories: ['focus'] },
    { content: 'cognitive growth', difficulty: 'beginner', categories: ['memory'] },
    { content: 'daily practice', difficulty: 'beginner', categories: ['focus'] },
    { content: 'lasting change', difficulty: 'beginner', categories: ['focus'] },
    { content: 'visual clarity', difficulty: 'beginner', categories: ['reading'] },
    { content: 'reading fluency', difficulty: 'beginner', categories: ['reading'] },
    { content: 'brain power', difficulty: 'beginner', categories: ['memory'] },
    { content: 'focused attention', difficulty: 'beginner', categories: ['focus'] },

    // 3 words — easy
    { content: 'improve your focus', difficulty: 'easy', categories: ['focus'] },
    { content: 'train your brain', difficulty: 'easy', categories: ['memory'] },
    { content: 'expand visual span', difficulty: 'easy', categories: ['reading'] },
    { content: 'build reading speed', difficulty: 'easy', categories: ['reading'] },
    { content: 'strengthen working memory', difficulty: 'easy', categories: ['memory'] },
    { content: 'boost mental clarity', difficulty: 'easy', categories: ['focus'] },
    { content: 'sharpen visual attention', difficulty: 'easy', categories: ['reading', 'focus'] },
    { content: 'increase reading fluency', difficulty: 'easy', categories: ['reading'] },
    { content: 'calm your mind', difficulty: 'easy', categories: ['focus'] },
    { content: 'build lasting habits', difficulty: 'easy', categories: ['focus'] },
    { content: 'train visual perception', difficulty: 'easy', categories: ['reading'] },
    { content: 'improve reading comprehension', difficulty: 'easy', categories: ['reading'] },
    { content: 'strengthen mental focus', difficulty: 'easy', categories: ['focus'] },
    { content: 'expand your vocabulary', difficulty: 'easy', categories: ['reading'] },
    { content: 'build strong habits', difficulty: 'easy', categories: ['focus'] },
    { content: 'increase brain speed', difficulty: 'easy', categories: ['memory'] },
    { content: 'develop reading skills', difficulty: 'easy', categories: ['reading'] },
    { content: 'sharpen your focus', difficulty: 'easy', categories: ['focus'] },
    { content: 'train your memory', difficulty: 'easy', categories: ['memory'] },
    { content: 'build cognitive strength', difficulty: 'easy', categories: ['memory'] },
    { content: 'improve visual tracking', difficulty: 'easy', categories: ['reading'] },
    { content: 'strengthen reading habits', difficulty: 'easy', categories: ['reading'] },
    { content: 'expand working memory', difficulty: 'easy', categories: ['memory'] },
    { content: 'build focused attention', difficulty: 'easy', categories: ['focus'] },

    // 4 words — medium
    { content: 'the brain learns quickly', difficulty: 'medium', categories: ['memory'] },
    { content: 'practice builds new habits', difficulty: 'medium', categories: ['focus'] },
    { content: 'attention shapes your learning', difficulty: 'medium', categories: ['focus'] },
    { content: 'memory improves with practice', difficulty: 'medium', categories: ['memory'] },
    { content: 'focus training builds discipline', difficulty: 'medium', categories: ['focus'] },
    { content: 'reading speed grows steadily', difficulty: 'medium', categories: ['reading'] },
    { content: 'visual attention expands naturally', difficulty: 'medium', categories: ['reading', 'focus'] },
    { content: 'learning becomes easier daily', difficulty: 'medium', categories: ['reading'] },
    { content: 'deliberate practice builds mastery', difficulty: 'medium', categories: ['focus'] },
    { content: 'calm minds process faster', difficulty: 'medium', categories: ['focus'] },
    { content: 'daily reading builds fluency', difficulty: 'medium', categories: ['reading'] },
    { content: 'focused practice improves memory', difficulty: 'medium', categories: ['memory', 'focus'] },
    { content: 'the eyes guide attention', difficulty: 'medium', categories: ['reading'] },
    { content: 'reading habits shape thinking', difficulty: 'medium', categories: ['reading'] },
    { content: 'visual training sharpens focus', difficulty: 'medium', categories: ['reading', 'focus'] },
    { content: 'strong habits build discipline', difficulty: 'medium', categories: ['focus'] },
    { content: 'the mind seeks patterns', difficulty: 'medium', categories: ['memory'] },
    { content: 'practice creates lasting change', difficulty: 'medium', categories: ['focus'] },
    { content: 'attention determines what sticks', difficulty: 'medium', categories: ['memory', 'focus'] },
    { content: 'reading builds mental stamina', difficulty: 'medium', categories: ['reading'] },
    { content: 'focused minds learn faster', difficulty: 'medium', categories: ['focus'] },
    { content: 'memory grows through use', difficulty: 'medium', categories: ['memory'] },
    { content: 'steady practice yields results', difficulty: 'medium', categories: ['focus'] },
    { content: 'the brain rewards repetition', difficulty: 'medium', categories: ['memory'] },

    // 5 words — advanced
    { content: 'consistent practice strengthens neural pathways', difficulty: 'advanced', categories: ['memory'] },
    { content: 'the brain adapts to challenges', difficulty: 'advanced', categories: ['memory'] },
    { content: 'focused attention improves comprehension speed', difficulty: 'advanced', categories: ['reading', 'focus'] },
    { content: 'visual training expands peripheral awareness', difficulty: 'advanced', categories: ['reading'] },
    { content: 'memory retention improves through repetition', difficulty: 'advanced', categories: ['memory'] },
    { content: 'reading fluency develops through practice', difficulty: 'advanced', categories: ['reading'] },
    { content: 'calm minds absorb information faster', difficulty: 'advanced', categories: ['focus'] },
    { content: 'daily habits shape long-term memory', difficulty: 'advanced', categories: ['memory'] },
    { content: 'deliberate practice reshapes neural pathways', difficulty: 'advanced', categories: ['memory'] },
    { content: 'steady focus improves reading comprehension', difficulty: 'advanced', categories: ['reading', 'focus'] },
    { content: 'the brain rewards consistent repetition', difficulty: 'advanced', categories: ['memory'] },
    { content: 'visual span grows through practice', difficulty: 'advanced', categories: ['reading'] },
    { content: 'calm attention absorbs information deeply', difficulty: 'advanced', categories: ['focus'] },
    { content: 'reading habits strengthen over time', difficulty: 'advanced', categories: ['reading'] },
    { content: 'focused practice builds lasting fluency', difficulty: 'advanced', categories: ['reading', 'focus'] },
    { content: 'the mind adapts to challenges', difficulty: 'advanced', categories: ['memory'] },
    { content: 'daily practice compounds over months', difficulty: 'advanced', categories: ['focus'] },
    { content: 'attention training improves working memory', difficulty: 'advanced', categories: ['memory', 'focus'] },
    { content: 'visual tracking becomes automatic eventually', difficulty: 'advanced', categories: ['reading'] },
    { content: 'reading speed follows comprehension gains', difficulty: 'advanced', categories: ['reading'] },
    { content: 'strong habits require consistent practice', difficulty: 'advanced', categories: ['focus'] },
    { content: 'the eyes learn to anticipate', difficulty: 'advanced', categories: ['reading'] },
    { content: 'memory consolidation happens during rest', difficulty: 'advanced', categories: ['memory'] },
    { content: 'focused reading builds deep understanding', difficulty: 'advanced', categories: ['reading', 'focus'] },

    // 6 words — expert (elite/master fall back to this tier)
    { content: 'the brain adapts through daily practice', difficulty: 'expert', categories: ['memory'] },
    { content: 'visual attention expands with deliberate training', difficulty: 'expert', categories: ['reading', 'focus'] },
    { content: 'memory strengthens through consistent focused practice', difficulty: 'expert', categories: ['memory', 'focus'] },
    { content: 'reading comprehension improves with steady practice', difficulty: 'expert', categories: ['reading'] },
    { content: 'neuroscience shows practice reshapes the brain', difficulty: 'expert', categories: ['memory'] },
    { content: 'focused practice builds long-term cognitive strength', difficulty: 'expert', categories: ['focus', 'memory'] },
    { content: 'psychology shows motivation drives lasting change', difficulty: 'expert', categories: ['focus'] },
    { content: 'learning deepens through active engaged practice', difficulty: 'expert', categories: ['reading'] },
    { content: 'deliberate practice reshapes the brain permanently', difficulty: 'expert', categories: ['memory'] },
    { content: 'visual attention expands through consistent training', difficulty: 'expert', categories: ['reading', 'focus'] },
    { content: 'the mind learns what it repeats', difficulty: 'expert', categories: ['memory'] },
    { content: 'reading fluency grows through daily practice', difficulty: 'expert', categories: ['reading'] },
    { content: 'calm focus produces the clearest thinking', difficulty: 'expert', categories: ['focus'] },
    { content: 'neural pathways strengthen with each repetition', difficulty: 'expert', categories: ['memory'] },
    { content: 'working memory improves through active practice', difficulty: 'expert', categories: ['memory'] },
    { content: 'the brain adapts to sustained challenge', difficulty: 'expert', categories: ['memory'] },
    { content: 'attention span grows with deliberate training', difficulty: 'expert', categories: ['focus'] },
    { content: 'reading comprehension deepens through focused practice', difficulty: 'expert', categories: ['reading', 'focus'] },
    { content: 'visual span training improves overall fluency', difficulty: 'expert', categories: ['reading'] },
    { content: 'consistent habits outperform sporadic intense effort', difficulty: 'expert', categories: ['focus'] },
    { content: 'daily reading builds long-term cognitive strength', difficulty: 'expert', categories: ['reading', 'memory'] },
    { content: 'focused minds process information more efficiently', difficulty: 'expert', categories: ['focus'] },
    { content: 'the science of reading supports practice', difficulty: 'expert', categories: ['reading'] },
    { content: 'memory retention strengthens through spaced repetition', difficulty: 'expert', categories: ['memory'] },
  ],
})
