-- ─────────────────────────────────────────────────────────────────────────────
-- 20260809000001_add_document_visual_learning_fields
--
-- "Read less, remember more" — four new fields generated by the SAME
-- single Claude Haiku call quantum_documents rows already come from (no
-- new AI call, no schema replacement). All nullable and purely additive:
-- every existing row keeps working unchanged (getQuantumDocumentById.ts
-- treats a null value here exactly like a pre-upgrade row, never a
-- validation failure).
--
-- keyword_icons is a separate `word -> icon name` map rather than
-- changing the shape of the existing `keywords` column (a native
-- Postgres text[], not jsonb) — that would require converting every
-- existing row's column type. Looking up keyword_icons->>word at read
-- time (falling back to a generic icon when absent) gets the same
-- result with zero migration risk to existing data.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.quantum_documents
  ADD COLUMN one_sentence_summary text,
  ADD COLUMN short_story text,
  ADD COLUMN recall_questions text[],
  ADD COLUMN keyword_icons jsonb;
